### ISSUE TITLE
Consider including singular template in boiler-plate theme

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/create-block-theme#103]
Since it's not currently possible to create a singular or single post without the Gutenberg plugin it would be a more complete experience to create an empty theme if singular were present when generating an empty theme.

This would be a short term need since there should be a mechanism for creating a single post and single CPT template once Gutenberg is merged for 6.1

**Comment by mikachan** [comment]
I believe you can now add single templates in 6.1, so I'm going to close this. Please re-open if you think this is still necessary!
