### ISSUE TITLE
Overwrite option deletes some important keys

### ISSUE THREAD

**Issue by LukaszJaro** [WordPress/create-block-theme#106]
Overwrite
[Save USER changes as THEME changes and delete the USER changes. Your changes will be saved in the theme on the folder.]

Removes the following:
- "$schema": "https://schemas.wp.org/trunk/theme.json",
- "useRootPaddingAwareAlignments": true, (I think part of this issue is schema has to be updated "Property useRootPaddingAwareAlignments" is not allowed.)

Also puts version key all the way at the bottom of the theme.json?

- "version": 2

I have been following similar setup to https://github.com/WordPress/twentytwentythree/blob/trunk/theme.json

Besides that it works pretty well!

**Comment by matiasbenedetto** [comment]
This should be fixed by https://github.com/WordPress/create-block-theme/pull/178.
Feel free to re-open this if it's still an issue.
