### ISSUE TITLE
Discussion: Does Create Block Theme warrant it's own top level menu item?

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/create-block-theme#123]
Initially, Create block theme had one theme page. Now it has three. 

Is now a good time to move the menu item to its own top-level menu item, after Appearance, to handle the three current pages, and any possible future pages?

**Comment by richtabor** [comment]
Isn't block theme creation going to be part of the site editor experience in time?

**Comment by jonathanbossenger** [comment]
As far as I know, yes. What I don't know right now is how much of what Create Block Theme does will be included in core, and when. 

I look at Create Block Theme as a feature plugin, similar to how the Gutenberg plugin is developed separately from core (maybe this is wrong?). But I like the idea that developer-focused features keep being added to the plugin, that may eventually be merged into core. However, some of them might not, as traditionally developer-focused features have not become core features. 

So I'm thinking about the long-term usability of Create Block Theme. If it's something that is going to be around for a bit, perhaps it makes sense to give it its own "identity" and creating a separate menu item would help with that.

**Comment by MaggieCabrera** [comment]
This is the issue where this was discussed: https://github.com/WordPress/gutenberg/issues/39189

**Comment by jonathanbossenger** [comment]
Thanks, @MaggieCabrera. It seems the general consensus there was that the features in Create Block Theme are going to be "plugin territory" only, for at least some time yet.

**Comment by pbking** [comment]
CBT is being reduced back down to a single page, with additional availability in the Editor.  These places are likely to remain, though the contents and purpose of the admin page is likely to change and grow.
