### ISSUE TITLE
Manage fonts: Disallow duplicate fonts

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/create-block-theme#130]
Currently the plugin has no mechanism to identify the duplicate fonts, and it lets duplicate fonts to be added.

<img width="545" alt="image" src="https://user-images.githubusercontent.com/1935113/197736437-1abdbc1e-d57e-480f-ab72-19bd31523ee6.png">

It can be improved by identifying the duplicates (the google fonts) with name or some other information such as fontID, and disable them to be added again to the theme (and may be a label indicating it already added to the theme, to avoid confusion of why a font is disabled).

<img width="545" alt="image" src="https://user-images.githubusercontent.com/1935113/197737029-1d0ef348-42ed-4aaf-a882-cae62c9dc1f3.png">

**Comment by mikachan** [comment]
As this plugin now uses the native Font Library to manage fonts, this issue no longer applies.
