### ISSUE TITLE
I18N: Some new UI strings are not translatable

### ISSUE THREAD

**Issue by alexclassroom** [WordPress/create-block-theme#139]
The uploaded screenshot shows some UI strings cannot be translated, please make the following UI strings translatable.
- Info
- This is a list of your font families listed in the theme.json file of your theme.
- If your theme.json makes reference to fonts providers other than local they may not be displayed correctly.
- These are the fonts currently embedded in your theme
- Weight
- Preview
- Remove Font Family
- Remove
- This action will delete the font definition and the font file assets from your theme.
- Are you sure you want to delete "style-name" variant of "font-name" from your theme?
- Are you sure you want to delete "font-name" from your theme?

![gutenberg l - 20221026 - 132257](https://user-images.githubusercontent.com/11472643/198130296-decb3ae8-577f-4760-9232-40daa45169d2.png)
![gutenberg l - 20221026 - 133423](https://user-images.githubusercontent.com/11472643/198132011-136f85c6-356b-4370-a0e1-5bb068f9ac8c.png)

**Comment by matiasbenedetto** [comment]
Hi @alexclassroom, thanks for the detailed description.
Is this still an issue?

If I run `wp i18n make-pot . languages/create-block-theme.pot` like [here](https://developer.wordpress.org/cli/commands/i18n/)  I get those strings in the pot file.

![image](https://user-images.githubusercontent.com/1310626/199233687-316242f8-3c9e-4f2a-920e-256c7c583c38.png)

**Comment by alexclassroom** [comment]
Based on the current version 1.3.7, even if we can use WP-CLI to make POT file including these UI strings but they do not exist in its owned [GlotPress project](https://translate.wordpress.org/projects/wp-plugins/create-block-theme/). This means the end users still cannot see these UI strings' translations when they use the latest language packs.

**Comment by matiasbenedetto** [comment]
Hi @alexclassroom are you able to test if this could solve the problem? https://github.com/WordPress/create-block-theme/pull/145
I'm not sure how could I test it. Thanks!
