### ISSUE TITLE
Manage fonts: Import Variable Font Files

### ISSUE THREAD

**Issue by bgardner** [WordPress/create-block-theme#149]
From what I can tell, it is not possible to import variable font files. Is there a plan to build that option into the plugin?

**Comment by colorful-tones** [comment]
I second this. ➕

**Comment by matiasbenedetto** [comment]
Currently, as with any other font file, you can upload the variable font assets using the “Add Local Font” option.
Google Fonts is not exposing the variable fonts through the API yet, but you can download the variable version of the font and upload it manually using the "Add local font" option of the plugin.

The plugin will add the font definition and asset just like any other type of font. You can use it just like that or adjust the options related to variable fonts by editing the theme.json file.

A recent article about this: https://themeshaper.com/2022/11/28/how-to-add-typographic-fonts-to-wordpress-block-themes/

**Comment by t-hamano** [comment]
Currently, Google Font API seems to [expose variable fonts](https://developers.google.com/fonts/docs/developer_api?apix_params=%7B%22capability%22%3A%5B%22VF%22%5D%7D#variable_fonts).

![google-font](https://github.com/WordPress/create-block-theme/assets/54422211/ab767a20-f566-4c58-a7d2-bfc1e0825656)

**Comment by t-hamano** [comment]
Note: There are typos in [the developer documentation](https://developers.google.com/fonts/docs/developer_api#variable_fonts), so be sure to use the correct words when trying out the sample request URLs.

![variable-fonts](https://github.com/WordPress/create-block-theme/assets/54422211/61324fd1-2996-48d2-90c8-86b776ccf8ab)

**Comment by mikachan** [comment]
As this plugin now uses the native Font Library to manage fonts, this issue no longer applies.
