### ISSUE TITLE
Validate the form

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/create-block-theme#15]
Right now we are not [validating](https://developer.wordpress.org/plugins/security/data-validation/) the form in any capacity. At the very least we need to make the name of the theme required and [sanitize](https://developer.wordpress.org/plugins/security/securing-input/) all the inputs submitted by the user.

**Comment by scruffian** [comment]
Done in https://github.com/Automattic/create-blockbase-theme/pull/18
