### ISSUE TITLE
Errors for "Create child of..." and "Clone..." options in new installation

### ISSUE THREAD

**Issue by weibeld** [WordPress/create-block-theme#158]
I currently face the following behaviour with version 1.3.8 of the plugin:
1. Create a new WordPress installation (with [Local](https://localwp.com/), see specs below)
2. Install the Create Block Them plugin
3. _Appearance > Create Block Theme > Create child of Twenty Twenty-Three_

This results in the below screen. The same happens with the _Clone Twenty Twenty-Three_ option.

![Screenshot 2022-12-01 at 02 00 25](https://user-images.githubusercontent.com/2396208/204941101-8b1cedfd-d47e-400e-b696-48782422c730.png)
![Screenshot 2022-12-01 at 02 00 50](https://user-images.githubusercontent.com/2396208/204941109-f978e718-6ec9-430e-ae34-1acf596f0aee.png)
![Screenshot 2022-12-01 at 02 01 04](https://user-images.githubusercontent.com/2396208/204941115-5ef511a6-84d8-4aef-b37a-cf319b947663.png)

WordPress specs:
- WordPress: v6.1.1
- PHP: v8.1.9
- MySQL: v8.0.16
- Local: v6.5.2

What could be the reason for this error?

**Comment by antonyjsmith** [comment]
On the Create Child Theme it's looking for the screenshot.png which is what causes the fatal error. I updated the path in .../class-create-block-theme-admin.php to use a generic image in the assets folder and it runs fine. Will try put a pull request together when I get chance!

**Comment by jffng** [comment]
I think this is fixed by #250, please re-open if you continue to experience the issue with the latest plugin version. Thanks!
