### ISSUE TITLE
Warnings for dependencies

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/create-block-theme#16]
We should alert the user when any of the dependencies are not present:

- Check that GB is installed, active and is the latest version (or one we define is needed for the plugin)
- Check that Blockbase is installed. Maybe warn the user if the version is not the latest, but allow them to use it if it's not.
- Check that the active theme is Blockbase or one of its children

**Comment by pbking** [comment]
With this change we are now allowing this to work for ANY block theme and the plugin is disabled if it is not a block theme.  I think this addressed the 2nd and 3rd points.

Regarding the first we do still require Gutenberg and probably a specific version though I'm not sure what exactly.  We should indeed test for that.

**Comment by MaggieCabrera** [comment]
Closing as this is no longer relevant
