### ISSUE TITLE
Cleanup Theme Export

### ISSUE THREAD

**Issue by mikachan** [WordPress/create-block-theme#162]
Currently, an exported theme includes attributes such as `ref` and `id` for certain blocks, but these have no context outside of the environment where the theme was built. They can also break some blocks (a `ref` in a nav block that doesn't exist on a different WordPress instance will currently cause the nav block to break).

Here are the cases I can think of, but there may be more:

- [x] Remove `ref` attributes from the Navigation block
- [x] Remove `id` attributes from Image and Cover blocks
- [x] Remove `wp-image-[id]` classes from Image and Cover blocks
- [x] Remove `category` IDs from query blocks
- [x] Remove `taxQuery` attribute from query blocks
- [x] ~Remove `queryId` attributes from Query block~ I don't think this needs removing, see https://github.com/WordPress/gutenberg/issues/42730#issuecomment-1428524380 for more details.

**Comment by MaggieCabrera** [comment]
I think this could be a gutenberg PR, since this plugin is already using the export functions, it makes sense that what gets exported is usable outside of the context where it was exported from. Do you agree @scruffian ?

**Comment by scruffian** [comment]
I agree!

**Comment by mikachan** [comment]
Makes sense! I'll replicate the issue over there.

**Comment by mikachan** [comment]
Already exists 😁 https://github.com/WordPress/gutenberg/issues/42730
