### ISSUE TITLE
Ability to save template changes

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/create-block-theme#163]
Original Tweet suggestion from @ciorici: https://twitter.com/ciorici/status/1603366366609920000?s=20&t=QTFjskYeDw6_26_QmjsGDA

![update-template-file](https://user-images.githubusercontent.com/405912/207916345-959a823f-fd91-4b68-a37b-b6ae4ab5f619.jpeg)

The ability to customize template parts is already available as a feature of Site Editing. However, for theme builders it would expedite workflows to have the ability to overwrite template parts directly within the Site Editor.

Alongside the “Clear customizations” it would be possible to add another option for “Overwrite with new customizations”. This would be a destructive action and immediately overwrite the entire template part in the theme.

**Comment by colorful-tones** [comment]
It looks like the ‘Clear customizations’ code lives here in Gutenberg:
https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/template-details/template-areas.js

**Comment by colorful-tones** [comment]
I’m wondering how this functionality might be added from a technical aspect. I believe we would likely have to pull in the whole `@wordpress/edit-site` package and possibly integrate the local store, which would likely get messy. I’m no expert though and would like to hear some other ideas (if any). 🤔 

It might be easier to try and leverage Filesystem API (PHP-based) and surface a unique interface elsewhere in the Create Block Theme plugin’s existing admin settings pages.

**Comment by matiasbenedetto** [comment]
>  for theme builders it would expedite workflows to have the ability to overwrite template parts directly within the Site Editor.

@colorful-tones isn't this behavior you describe covered by the "Overwrite" option of the plugin?

**Comment by pbking** [comment]
A "save changes" option is now available in the Site Editor interface.   I believe this covers the use case described above, though in a different way.

If it doesn't please reopen this issue.

**Comment by vegetable-bits** [comment]
@pbking I think it doesn't do the same as original requested. I'm using git deployments, so I do my template changes locally in a safe enviorment. I'd like to have a more "automatic" way to sync my changes to filesystem. With a git workflow i don't mind auto the missing possibility to revent anything from the ui, since i can simply revent changes / commits.

There should be at least a API so we can do something like:

```php
/**
 * Export template to filesystem
 */
add_action('save_post', function ($post_id) {
    // check its a template handelt
    if (get_post_type($post_id) === 'wp_template') {
        // call create-block-theme api to sync changes
    }
});
```
