### ISSUE TITLE
Remove Font Family option does not remove fonts from /assets/

### ISSUE THREAD

**Issue by bgardner** [WordPress/create-block-theme#164]
When you click Remove Font Family (or Remove for individual), the fonts are not removed from the /assets/ directory. While they are no longer listed on the Manage Theme Fonts screen, this is not expected behavior. Imagine a user adding/removing 100 fonts, and having those files accumulate in the /assets/ directory.

**Comment by colorful-tones** [comment]
> When you click Remove Font Family (or Remove for individual), the fonts are not removed from the /assets/ directory. 

I just tested and verified that the font file(s) are not removed.

> Imagine a user adding/removing 100 fonts, and having those files accumulate in the /assets/ directory.

I agree this is not ideal, but not sure how critical it may be overall. It would mostly concern me for hosting providers. Ultimately, it would be great to see the file(s) removed completely.

**Comment by tinjure20** [comment]
I can also confirm that I was not able to remove fonts from the `assets/fonts` folder with plugin's **Remove Font Family** option.
