### ISSUE TITLE
Include a basic theme thumbnail image with boilerplate theme

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/create-block-theme#169]
It would be great if a simple placeholder image were included with the blank/boilerplate theme.

Bonus points if it could be replaced with a custom image by the user.

**Comment by mikachan** [comment]
Opened a PR for adding a placeholder image: https://github.com/WordPress/create-block-theme/pull/193

> Bonus points if it could be replaced with a custom image by the user.

This will be covered with https://github.com/WordPress/create-block-theme/pull/185!
