### ISSUE TITLE
Adding fonts removes schema (and appearanceTools and anything else?) from theme.json

### ISSUE THREAD

**Issue by TechDotHaus** [WordPress/create-block-theme#170]
Hi.

Here's what I do. 

Create a blank theme. Edit: Then, of course, switch to that theme.

Then I add a font.

Then I look at the theme.json, and the schema and "settings": "appearanceTools" parts are now missing. They were there before I added a font.

**Comment by jffng** [comment]
Tested and verified this is an issue, looking into it.
