### ISSUE TITLE
Clean markup

### ISSUE THREAD

**Issue by jffng** [WordPress/create-block-theme#175]
Sometimes block markup contains site specific references, e.g. the nav block contains a ref, or an image block has a specific id. It would be useful for the plugin to have an option that strips the markup of these site-specific references.

**Comment by mikachan** [comment]
There's already an issue open for this in GB: https://github.com/WordPress/gutenberg/issues/42730

(I opened a similar issue here! https://github.com/WordPress/create-block-theme/issues/162)

**Comment by jffng** [comment]
Oh perfect, thanks @mikachan !
