### ISSUE TITLE
Creating style variations clears all customizations

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/create-block-theme#180]
When creating a new style variations, all customizations on templates will be cleared. 
This is especially frustrating when starting with a blank theme, working on said new theme, adding a style variant, and all work is gone…

Quick fix: Add a info text.
<img width="535" alt="image" src="https://user-images.githubusercontent.com/17861443/214074386-f732ed46-bc5e-475d-b8a7-e53f19a3081e.png">

Better solution: Don't let this option remove the customizations.

**Comment by pbking** [comment]
Since templates have nothing to do with style variations I agree, creating a style variation SHOULD continue to (re)move the STYLE changes, however the TEMPLATING changes shouldn't be touched in that situation.

**Comment by beafialho** [comment]
> Since templates have nothing to do with style variations I agree, creating a style variation SHOULD continue to (re)move the STYLE changes, however the TEMPLATING changes shouldn't be touched in that situation.

> Better solution: Don't let this option remove the customizations.

I agree, creating and saving a style variation should not touch the templates.
