### ISSUE TITLE
Adding and deleting fonts is not working locally or live

### ISSUE THREAD

**Issue by kauaicreative** [WordPress/create-block-theme#181]
Adding and deleting fonts is not working locally or live
- **local** - Local by flywheel. mac M1. chmod -R 777. PHP7.4 and PHP8.0, nginx and appache 
- **live** - DigitalOcean/runcloud.io

No errors or warnings are reported in console or log
Tested both wordpress.org/plugins and current trunk here.

**Comment by hanneslsm** [comment]
@kauaicreative What browser are you using? 
I wonder if we have the same issue. Fonts are not working for me in Firefox and Safari, but with Chrome / Brave.

**Comment by kauaicreative** [comment]
@HannesDev I am using Brave/Chrome. For some reason it started working this morning. Not sure what changed.

**Comment by matiasbenedetto** [comment]
:wave: Hi @kauaicreative and @HannesDev, please try again after updating the plugin to the latest version.
If it is still not working, please post this info to help others to debug:
- Which is the error message you get
- Operative system you are using
- How are you running WordPress

Thanks!

**Comment by hanneslsm** [comment]
I found the issue why it wasn't working for me: I installed a font but with only one style (600) and weight (italic). In my style the font settings for headings are set to default. In Chrome it takes the installed font automatically but for Safari and Firefox I manually have to select also the correct style and weight in "appearance", otherwise it just won't display the installed font.

**Comment by matiasbenedetto** [comment]
> I found the issue why it wasn't working for me: I installed a font but with only one style (600) and weight (italic). In my style the font settings for headings are set to default. In Chrome it takes the installed font automatically but for Safari and Firefox I manually have to select also the correct style and weight in "appearance", otherwise it just won't display the installed font.

Thanks for the info @HannesDev.
I'm closing this issue, feel free to re-open it if the problem persists.
