### ISSUE TITLE
Merge Clone and Export options

### ISSUE THREAD

**Issue by jffng** [WordPress/create-block-theme#186]
Currently Export and Clone are two different options but they effectively do the same thing. Clone just allows you to overwrite the theme metadata (name, author, etc.).

I think it would make sense to merge these two options, and just have the form pre-filled with existing theme metadata. And if the user wants, they can overwrite the metadata if they want. 

What do others think?

**Comment by mikachan** [comment]
Yeah, I like the idea of merging these two options, makes sense to me 👍

**Comment by matiasbenedetto** [comment]
I agree with your proposal if the difference is just the ability to edit the metadata.

**Comment by tinjure20** [comment]
IMO, the three options: export, clone and rewrite could be combined in one, with a select drop-down menu added in the form, to allow users to choose which function to perform. Depending on the selected entry, display the form (for clone) or the notification (to rewrite).

If pattern feature (similar to style variation) is added to the plugin, then it actually allows creating a block theme without writing code. This could be huge for average WordPress users with no/little coding skill.

**Comment by pbking** [comment]
This has been merged in the Site Editor interface.  Closing as complete.
