### ISSUE TITLE
Theme font deleted when font weight removed

### ISSUE THREAD

**Issue by bgardner** [WordPress/create-block-theme#190]
When fonts have been added and then removed individually, the font that ships with the theme also gets removed. See video below, where my theme ([Powder](https://wordpress.org/themes/powder/)) ships with Outfit, then I add 4 weights of Figtree, delete one, and then Outfit completely disappears (is also deleted). This does not seem to happen when the Remove Font Family option is used.

https://user-images.githubusercontent.com/486261/214597544-8d334157-8ab2-49f5-86e9-34739791e801.mp4

**Comment by matiasbenedetto** [comment]
I was able to reproduce the issue. I will be submitting a fix shortly.
