### ISSUE TITLE
Consider adding input for theme credits

### ISSUE THREAD

**Issue by jffng** [WordPress/create-block-theme#195]
It might be useful to add a form input so users can append credits (for fonts, images, etc) or other information to the readme when they export the theme.

- [x] Handle license info for Google fonts: https://github.com/WordPress/create-block-theme/pull/298
- [x] Handle license info for local fonts https://github.com/WordPress/create-block-theme/issues/348
- [x] Handle license info for media https://github.com/WordPress/create-block-theme/pull/380

**Comment by mikachan** [comment]
I think we can close this now as both fonts and images can now be credited from within the plugin.
