### ISSUE TITLE
Should we implement an API instead of relay on HTML forms for client - server communication ?

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/create-block-theme#198]
We are not calling the backend a-synchronically from the client but relying on traditional HTML forms to post data to the backend PHP code. This produces spaghetti code and, for that reason, harder-to-read code and more prone to errors.

Implementing the backend functionality as a Rest API could simplify the code and enable us to implement more complex functionalities in the plugin with less effort.

**Comment by jffng** [comment]
Yes, would love to see this / help work on it. Implementing a REST API will also make re-using some functionality easier across different parts of the app.

**Comment by pbking** [comment]
Implemented here: https://github.com/WordPress/create-block-theme/pull/368

Closing as fixed
