### ISSUE TITLE
Evaluate if and how to implement code splitting for the React App

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/create-block-theme#205]
More context on: https://github.com/WordPress/create-block-theme/pull/194#pullrequestreview-1279492755

**Comment by t-hamano** [comment]
I used the following command to find out which modules were affected:

```
npm run build -- --webpack-bundle-analyzer
```

![analyzer](https://user-images.githubusercontent.com/54422211/216616761-3cc4e010-b69f-41ff-8123-ad8c633c2342.png)

We can see that the `fallback-fonts-list.json` file is the primary cause of the large build size. Therefore, I think splitting the React component would not be effective.

This file has a file size of 1.10 MB even before build. And this file is imported here:

https://github.com/WordPress/create-block-theme/blob/5008d6cb50f0d796567a86b8a92154d0b0a3f889/src/google-fonts/index.js#L8

This file is generated from data obtained from the Google Web Font API. However, only some properties of this file are used in the React app.

By narrowing down to the necessary data, it may be possible to reduce the bundle size.

**Comment by t-hamano** [comment]
Still testing, but #209 confirms that the build folder size can be reduced from about 110KB to 120KB.
