### ISSUE TITLE
Can't create child theme

### ISSUE THREAD

**Issue by VerityCantare** [WordPress/create-block-theme#207]
I'm using 1.4.0 from the Wordpress.org repository.

I'm trying to create a child theme of twenty twenty-three and it keeps giving me some sort of security error. I've tried it in Firefox and Opera, with all the various security enabled and without it. Yes, it's a live site (sorta). I tried it on another site that has almost nothing installed, just Bulletproof Security and Cloudflare and it still didn't work. 

It created a blank theme just fine.

Any thoughts?

![Screenshot - 2_2_2023 , 2_31_00 PM](https://user-images.githubusercontent.com/124307755/216741356-2d505679-62a9-4400-88b8-1ea89bdd7f23.jpg)

![Screenshot - 2_2_2023 , 2_30_36 PM](https://user-images.githubusercontent.com/124307755/216444037-e345ddaf-e4ed-4002-97a6-7cc8d536d1f5.jpg)

**Comment by jffng** [comment]
Hi @VerityCantare thanks for the report, looking into it.

I wonder if this could have something to do with the way we are handling the form request + returning the data.

It makes sense that creating a blank theme works, since that option doesn't actually export / return a theme zip.

**Comment by pbking** [comment]
This interface is depreciated and construction of a child theme workflow is slightly different.  This doesn't seem relevant any more; closing.
