### ISSUE TITLE
"Create blank theme" throws errors in class-create-block-theme-admin.php: Undefined variable $zip / Call to a member function addFile() on null 

### ISSUE THREAD

**Issue by pax** [WordPress/create-block-theme#212]
Encountered the following errors when trying to **Create blank theme** (Generate a boilerplate "empty" theme inside of this site's themes directory) - tried both on a macOS local instance and a rather popular shared hosting account. 

> Warning: Undefined variable $zip in .../wp-content/plugins/create-block-theme/admin/class-create-block-theme-admin.php on line 312
> ... 
> Fatal error: Uncaught Error: Call to a member function addFile() on null in .../wp-content/plugins/create-block-theme/admin/class-create-block-theme-admin.php:312

![class-create-block-theme-admin.php fatal error](https://user-images.githubusercontent.com/116795/217254568-d8b96d6a-e21e-4f53-8304-e30166b7520a.png)

**Comment by oskosk** [comment]
Fixed by #250

**Comment by jffng** [comment]
Thank you @oskosk and @pax for the report! Please re-open if you continue to experience the issue, but should be resolved in a patch update that will be released shortly (1.6.2).
