### ISSUE TITLE
"Export" option when editing a child theme should create a stand-alone theme.

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/create-block-theme#215]
## What ?
"Export" option when editing a child theme should create a stand-alone theme.

## Why ?
Because we have another option to create another child theme "create sibling theme".

## Current behavior
The "Export" option seems to be working mostly ok creating a stand-alone theme when editing a child theme but the data in style.css seems to be wrong. Particularly the "Template" item. Example:

```
/*
Theme Name: tt3child
Theme URI: 
Author: 
Author URI: 
Description: 
Requires at least: 5.8
Tested up to: 5.9
Requires PHP: 5.7
Version: 0.0.1
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Template: twentytwentythree
Text Domain: tt3child
Tags: one-column, custom-colors, custom-menu, custom-logo, editor-style, featured-images, full-site-editing, rtl-language-support, theme-options, threaded-comments, translation-ready, wide-blocks
*/
```

**Comment by pbking** [comment]
This workflow has been removed/depreciated.
Closing
