### ISSUE TITLE
Should we automate the escaping of texts for translation?

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/create-block-theme#221]
Should we automate the escaping for translation of all the texts included in templates and template parts?

Knowing that we can't escape for translation the HTML files from templates and templates parts. We would need to transform the templates and template parts containing any text to a pattern and link the pattern created to the template. The process would be very similar to the one applied to the media bundler: https://github.com/WordPress/create-block-theme/pull/213.

**Comment by matiasbenedetto** [comment]
Closed as duplicated of: https://github.com/WordPress/create-block-theme/issues/174

**Comment by jffng** [comment]
Thanks @matiasbenedetto I will clarify 174 a bit.
