### ISSUE TITLE
Remove the fallback implementations when WP_HTML_Tag_Processor is available in core (6.2)

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/create-block-theme#225]
When [WP_HTML_Tag_Processor](https://github.com/WordPress/gutenberg/pull/42485) is available in WordPress core (6.2), we could remove the fallback implementation of dom parsing using DOMDocument and/or regex introduced in this PR https://github.com/WordPress/create-block-theme/pull/213 to circumvent the lack of that tool when Gutenberg is not installed.

**Comment by pbking** [comment]
Complete. :) Done with 2.0 release which raised requirements to WordPress 6.5
