### ISSUE TITLE
Font Management: accessibility improvements

### ISSUE THREAD

**Issue by mikachan** [WordPress/create-block-theme#230]
I noticed a couple of accessibility improvements that could be made to the font management page:

- [ ] The expand/collapse icon on each font family heading is missing a label. I think we should add a label based on [these best practices](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#icon_buttons).

<img width="362" alt="image" src="https://user-images.githubusercontent.com/1645628/219607833-bacd8a07-f662-46d2-a431-5a096e296def.png">

- [ ] It would be good to add the name of the font family in each remove button, so it's clear which font family they are linked to. For example, add an `aria-label` with the contents, "Remove DM Sans font family".

<img width="269" alt="image" src="https://user-images.githubusercontent.com/1645628/219614141-3eabfdfd-d13a-4f34-be15-64d47814c0f7.png">

- [ ] Similar to above, it would be good to add an `aria-label` to the font face buttons too.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/1645628/219614392-4ced68d3-0fda-4850-af2b-f665e7c232be.png">

- [ ] The tab order of the font size range control is reversed because the flex-direction is set to `row-reverse`. This is probably because the `RangeControl` component only allows for the input to be shown on the right, and in this case, it works better on the left. I'm not sure what's possible here but thought it was worth mentioning. Maybe we could look into changing the tab order somehow.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/1645628/219611600-ad3e7d19-203b-4e3f-89a1-adac671166b1.png">

**Comment by kishanjasani** [comment]
@mikachan there is one more accessibility related issue is with color contrast for buttons.

**Comment by kishanjasani** [comment]
@mikachan  For the last point, 

> The tab order of the font size range control is reversed because the flex-direction is set to row-reverse. This is probably because the RangeControl component only allows for the input to be shown on the right, and in this case, it works better on the left. I'm not sure what's possible here but thought it was worth mentioning. Maybe we could look into changing the tab order somehow.

Using the flex-direction property with values of row-reverse or column-reverse will create a disconnect between the visual presentation of content and DOM order. This will adversely affect users experiencing low vision navigating with the aid of assistive technology such as a screen reader. If the visual (CSS) order is important, then screen reader users will not have access to the correct reading order.

**Alternative solution,**
So we can add `RangeControl` with `withInputField={ false }` props. Currently, It's `withInputField={ true }`

We can use `AllInputControl` or `InputControls` with the `RangeControl` to deal with accessibility issue.

Waiting for other suggestions! 😊👋

**Comment by mikachan** [comment]
Thanks for your input, @kishanjasani!

> We can use AllInputControl or InputControls with the RangeControl to deal with accessibility issue.

I like the sound of these suggestions. Which do you think would work best out of `AllInputControl` and `InputControl`? I'm thinking `InputControl` with `RangeControl` would work, but I've not used `AllInputControl` before.

**Comment by mikachan** [comment]
As this plugin now uses the native Font Library to manage fonts, this issue no longer applies.
