### ISSUE TITLE
CSS Linter problem with named colors

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/create-block-theme#264]
CSS Linter doesn't let you use color names as "white".

Example CSS definition:
`background-color: white;`

Error message:

```
create-block-theme$ npm run lint:css:fix

> create-block-theme@1.6.3 lint:css:fix
> npm run lint:css -- --fix


> create-block-theme@1.6.3 lint:css
> wp-scripts lint-style


src/fonts-sidebar/fonts-sidebar.css
 13:20  ✖  Unexpected named color "white"  color-named

1 problem (1 error, 0 warnings)
```

**Comment by madhusudhand** [comment]
I think it is good to have this rule and always define hex/rgb color values.

**Comment by matiasbenedetto** [comment]
> I think it is good to have this rule and always define hex/rgb color values.

Why? named colors are valid CSS / HTML, right?

**Comment by t-hamano** [comment]
I think the focus is not on whether named colors are correct as CSS, but on what rules to unify.

Create Block Theme project uses `@wordpress/scripts` in Lint, and this package uses `@wordpress/stylelint-config` as the default lint rule. And [named colors are prohibited](https://github.com/WordPress/gutenberg/blob/7e4fd671b091ea8679481081c9b68e300f38c8df/packages/stylelint-config/index.js#L23) in `@wordpress/stylelint-config`.

Unless you have a special reason to use named colors, I would personally recommend leaving the default lint rules in place.
