### ISSUE TITLE
Use css grid system instead of table in font-management UI

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/create-block-theme#266]
Tables are great for large screens, but they aren't flexible and doesn't fit well in small screens.
Switching to grid system should provide a better user experience in small screens (mobile or tabs)

<img width="347" alt="image" src="https://user-images.githubusercontent.com/1935113/223962568-d7d0dce9-be8d-4c5b-be0a-0a0385fdb117.png">

**Comment by t-hamano** [comment]
Since this feature has been integrated into the native font library, can this issue be closed?

**Comment by pbking** [comment]
Yup.  Closing.
