### ISSUE TITLE
Template part has been deleted or is unavailable: header

### ISSUE THREAD

**Issue by base-creme** [WordPress/create-block-theme#27]
Hi !

I tried to make a child theme of Blockbase and I get these errors :

![Capture d’écran 2021-12-14 à 10 15 25](https://user-images.githubusercontent.com/53814375/145968878-588865bd-aaae-4319-b28d-98b7764df620.png)

I just modified the header to test a child theme.
Here is what I get in the zip file.

<img width="199" alt="Capture d’écran 2021-12-14 à 10 16 51" src="https://user-images.githubusercontent.com/53814375/145969121-9f7d6a70-e12e-40f4-9e07-638cfcc4dda0.png">

It's a basic WP 5.8.2 without any plugins installed, just for the try.

![Capture d’écran 2021-12-14 à 10 18 45](https://user-images.githubusercontent.com/53814375/145969456-88cbc8ca-45e9-47e4-95e0-0c4d4297b038.png)

What am I doing wrong ?

Thanks !

**Comment by MaggieCabrera** [comment]
Hi! Thanks for testing. This is a known bug in Gutenberg that has been recently fixed, try and download the latest from trunk or wait until the next GB version. This is the fix: https://github.com/WordPress/gutenberg/pull/36910

**Comment by base-creme** [comment]
Thanks Maggie ! When will be the next version available ?

**Comment by MaggieCabrera** [comment]
This fix is scheduled for 12.2, Gutenberg releases every two weeks give or take

**Comment by base-creme** [comment]
I confirm that it's working in version 12.2.
I now have trouble with the customisations I made on parent theme not applied on the child theme (color palette and fonts).
I opened a thread [here](https://github.com/Automattic/create-blockbase-theme/issues/29).

**Comment by pbking** [comment]
> I confirm that it's working in version 12.2.
