### ISSUE TITLE
Clone + Overwrite

### ISSUE THREAD

**Issue by pbking** [WordPress/create-block-theme#284]
Given the workflow: 
* Activate a Base Theme to start from (such as Blank Canvas)
* Make Changes using the Site Editor and save them
* (optional) Save the User changes to the activated Base Theme
* Clone the Theme (exporting it with a new name)

At this point a .zip file exists with the changes to the Theme, however those changes exist EITHER:
* In the user space 
* Saved in a modified version of the Base Theme

Unless we upload the newly exported theme .zip to the site we don't have those changes in the site.

I suggest a means of cloning the theme but keeping it on the site rather than exporting a .zip file.  This way changes can continue to be made to the theme and saved locally using the "overwrite" option which would overwrite to the NEW theme rather than to the original Base Theme.

This would also be an alternative to "Creating a Blank Theme" which is currently the only way to CREATE a new theme in the environment.

**Comment by jffng** [comment]
Would this solve https://github.com/WordPress/create-block-theme/issues/288, or is the use case different?

**Comment by pbking** [comment]
Yup, exactly that.

I don't know that it needs to be activated but at least installed.  This would definitely address that.

**Comment by pbking** [comment]
This as been accomplished in t[he move from wp-admin to site editor](https://github.com/WordPress/create-block-theme/pull/368).  

Closing this as complete (enough).
