### ISSUE TITLE
Consider adding option to edit themes post-export

### ISSUE THREAD

**Issue by mikachan** [WordPress/create-block-theme#286]
It would be nice if the plugin allowed users to edit themes created with the plugin after they have already been exported. This would give users a way to update themes at a later stage.

Based on this forum post: https://wordpress.org/support/topic/interesting-development-2/

**Comment by pbking** [comment]
I think that this would be answered by implementing this: https://github.com/WordPress/create-block-theme/issues/284

If there are any changes needed after "making" the theme then that theme being the activated theme (rather than the base theme) would allow the changes to be made after "exporting".

**Comment by mikachan** [comment]
Ah yeah, true! I think we can close this issue then and concentrate on https://github.com/WordPress/create-block-theme/issues/284 ✨
