### ISSUE TITLE
Child theme of blockbase theme : customizer not available anymore.

### ISSUE THREAD

**Issue by base-creme** [WordPress/create-block-theme#29]
Hi there !

I'm using blockbase theme and created a child theme with the create blockbase theme plugin.
When I activate my child theme, I don't have a full access to the customizer and the customization I made were not applied (background color, fonts…).

Here is what I see in the child theme :

![Capture d’écran 2021-12-22 à 15 02 43](https://user-images.githubusercontent.com/53814375/147104782-5fb0bed7-218b-42ca-aa77-1a41f0400eef.png)

![Capture d’écran 2021-12-22 à 15 03 06](https://user-images.githubusercontent.com/53814375/147104800-24ca0045-1267-4abe-acf2-c143b4b0f7b5.png)

And in the parent theme (blockbase) :

![Capture d’écran 2021-12-22 à 15 03 06](https://user-images.githubusercontent.com/53814375/147105034-becbd325-408d-4fa7-82e4-b19e0e0275e0.png)

![Capture d’écran 2021-12-22 à 15 05 13](https://user-images.githubusercontent.com/53814375/147105058-e9af8584-d691-462c-b965-efde5b78ae39.png)

What am I doing wrong ?

Thanks !

**Comment by MaggieCabrera** [comment]
You need to get the latest version of Blockbase, but this is not a plugin issue, so I'm closing this
