### ISSUE TITLE
Fatal error or network error

### ISSUE THREAD

**Issue by antonyjsmith** [WordPress/create-block-theme#30]
I've tried with 5.8.3, 5.9 rc-2 with and without Gutenberg installed. I'm getting a fatal error or just a blank page. The fatal error is the same as in #20

`Fatal error: Uncaught Error: Call to undefined function gutenberg_get_block_templates() in /home/digitaldepotco/public_html/betelgeuse/wp-content/plugins/create-blockbase-theme-trunk/index.php:156 Stack trace: #0 /home/digitaldepotco/public_html/betelgeuse/wp-content/plugins/create-blockbase-theme-trunk/index.php(245): gutenberg_edit_site_export_theme_create_zip('/tmp/betelgeuse...', Array) #1 /home/digitaldepotco/public_html/betelgeuse/wp-content/plugins/create-blockbase-theme-trunk/index.php(323): gutenberg_edit_site_export_theme(Array) #2 /home/digitaldepotco/public_html/betelgeuse/wp-includes/class-wp-hook.php(307): blockbase_save_theme('') #3 /home/digitaldepotco/public_html/betelgeuse/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #4 /home/digitaldepotco/public_html/betelgeuse/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #5 /home/digitaldepotco/public_html/betelgeuse/wp-admin/admin.php(175): do_action('admin_init') #6 /home/digitaldepotco/public_html/betelgeuse/wp-admin/themes.php( in /home/digitaldepotco/public_html/betelgeuse/wp-content/plugins/create-blockbase-theme-trunk/index.php on line 156`

**Comment by wingmatt** [comment]
Just ran into this myself. Same errors at the same line numbers.

If it's helpful, my server stack is: 

- Apache
- PHP 7.3.33
- MariaDB 10.3.28

**Comment by MaggieCabrera** [comment]
Is this still happening?
