### ISSUE TITLE
Template parts block crashes when switching to template edit mode in the post

### ISSUE THREAD

**Issue by t-hamano** [WordPress/create-block-theme#308]
This problem occurs on a clean install of WordPress 6.2 with only the Create Block Theme plugin activated.

### Step-by-step reproduction instructions

- Activate Twenty Tweny Three.
- Activate Create Block Theme plugin.
- Open a post/page.
- Open the template from the sidebar.
- Confirm that the template parts crash.
- Disable Create Block Theme plugin.
- Confirm that the template parts DON'T crash.

### Screencast

https://user-images.githubusercontent.com/54422211/231092831-51310af2-f0e7-4c03-90bd-d594bd2c569e.mp4

### Why?

This error does not occur if you comment out the following script:

https://github.com/WordPress/create-block-theme/blob/7d1a46de7ef372d4d43edb3b62effd9c434a7c8f/admin/class-create-block-theme-admin.php#L45-L47

This script depends on the `edit-site` package:
https://github.com/WordPress/create-block-theme/blob/7d1a46de7ef372d4d43edb3b62effd9c434a7c8f/src/plugin-sidebar.js#L2

There are two possible solutions:

- Don't load this script in the post editor.
- Don't depend on `edit-site` package. The following approaches may be available:
  ```javascript
  import {
  	PluginSidebar as PostPluginSidebar
  	PluginSidebarMoreMenuItem as PostPluginSidebarMoreMenuItem
  } from '@wordpress/edit-post';
  import {
  	PluginSidebar as SitePluginSidebar,
  	PluginSidebarMoreMenuItem as SitePluginSidebarMoreMenuItem
  } from '@wordpress/edit-site';

  const PluginSidebar = PostPluginSidebar === undefined 
  	? SitePluginSidebar
  	: PostPluginSidebar;

  const PluginSidebarMoreMenuItem = PostPluginSidebarMoreMenuItem === undefined 
  	? SitePluginSidebarMoreMenuItem
  	: PostPluginSidebarMoreMenuItem;
  ```

**Comment by matiasbenedetto** [comment]
> There are two possible solutions

The two options would be OK, the important part is not crashing the editor, but I prefer to have the button available in both places.

**Comment by t-hamano** [comment]
This code adds "Create Block Theme" menu, but I think it seems unnecessary in the post editor, as users may often run it after editing global styles and templates.

I would prefer not to enqueue this script in the post editor, what do you think?

**Comment by matiasbenedetto** [comment]
> I would prefer not to enqueue this script in the post editor, what do you think?

Sounds good :+1: , let's try that option.
