### ISSUE TITLE
Move CBT plugin UI to the Editor

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/create-block-theme#322]
## What ?
Currently, the experience is mainly in wp-admin, and only one functionality is working on the editor (Clone theme).

## Why ?
- Most of the WordPress website editing capabilities are being integrated into the editor.
- Adding theme editing capabilities with the plugin seems like a good next step in the way of improving the editor experience. 
- Makes the CBT user interface closer to the Gutenberg interface so migrating CBT theme editing capabilities to Gutenberg can be easier. 
- Forces us to improve the frontend/backend communication (currently using mostly HTML forms).

## An exploration

This is a little exploration showing a potential main CBT plugin sidebar screen and the export screen.
If you think it is worth continuing work on this or you have ideas to improve it share them here, please!

https://user-images.githubusercontent.com/1310626/231865810-2f8d67ee-f79a-4ab4-822c-e711676fded3.mp4

**Comment by pbking** [comment]
<img width="291" alt="image" src="https://user-images.githubusercontent.com/146530/231870709-3313d2ee-9b55-4f8d-854d-edab0526e4b2.png">

A minor change to make the options more 'shallow' and simpler would be to change "New" options from "export" to "clone" which would be the "export->folder->activate-after-export" option.  

Likewise perhaps "new" should only allow "folder->activate-after-export" option.

Maybe any "create" option (either clone or new) should prompt for metadata and expect a new and unique name.

Then the "export" option could be surfaced to the top level and would exclusively be to export the current state of the theme as a .zip.  Just like Gutenberg does, but with added value.  I think "exporting" to include the theme and user changes is problematic in the current incarnation.  Think of "exporting a PDF from Word".  You export a snapshot of the current state, not a combination of states (theme+user) as we allow for today.
