### ISSUE TITLE
Local Fonts: Make it possible to upload more than one font file at a time

### ISSUE THREAD

**Issue by beafialho** [WordPress/create-block-theme#330]
It's currently a bit cumbersome to add local fonts if we want to add a whole family. Would it be possible to upload a folder or more than one font file?

<img width="1018" alt="Captura de ecrã 2023-04-18, às 11 04 39" src="https://user-images.githubusercontent.com/65220155/232744286-fe5deaed-68ef-451d-a8db-aa95330ca657.png">

**Comment by t-hamano** [comment]
I believe the font management has been integrated into the native font library. Can we close this issue?

**Comment by matiasbenedetto** [comment]
Yes, we can close it now
