### ISSUE TITLE
Images are not placed in the assets folder on export

### ISSUE THREAD

**Issue by carolinan** [WordPress/create-block-theme#336]
Images from the wordpress.org pattern directory are not placed in the assets folder on export.

To reproduce:

Activate Twenty Twenty-Three
In any template in the site editor, add a pattern from the pattern directory that has an image,
For example Banners > Opening hours or Forest.
Save the template.

Try to export the theme using the plugin icon in the Site Editor.
I  got an error message saying "An error occurred while attempting to export the theme" and the browser console shows
Internal Server Error 500.

Go to the Admin > Appearance > Create block theme, and select export.

Check the content of the zip file.
The pattern was created with a local link, but the image is not in the folder.
`<!-- wp:cover {"url":"<?php echo esc_url( get_stylesheet_directory_uri() ); ?>/assets/images/forest.jpg","dimRatio":60,"minHeight":800,"align":"full"} -->`

**Comment by carolinan** [comment]
I made another test and images included from the media library are also not added to the zip file on export.

**Comment by carolinan** [comment]
I have updated to plugin version 1.8.2.
On my Mac, the images are correctly placed in the folder.
But on my PC, they are not.

WordPress 6.2
Create block theme 1.8.2
With and without Gutenberg Version 15.6.2 

I am logged to WP in as the admin user.

On windows, the site address is http://basic.wordpress.test/
on Mac it is http://localhost:10013/
Maybe the punctiunation matters? Or maybe there is a different path issue in the code that affects windows.

Windows 10 vs MacOS Ventura 13.3.1
Chrome

"Local":
nginx
MySQL 8.0.16
PHP: 8.0.22 and 7.4.3.0.
Multisite: No
Xdebug: On

**Comment by markhowellsmead** [comment]
I'm experiencing the same issue as originally reported with WordPress 6.3 and the latest version of the plugin. I've added images to image blocks in e.g. the footer and the plugin correctly modifies these and saves the pattern with the `get_stylesheet_directory_uri` paths. However, the files aren't copied into the assets/images folder. Although I'm specifically using SVGs, the same problem occurs with PNG and JPG files.
