### ISSUE TITLE
Theme name validation UX improvements

### ISSUE THREAD

**Issue by jffng** [WordPress/create-block-theme#339]
As a follow up to https://github.com/WordPress/create-block-theme/pull/304 there are a couple improvements we could make to the UX:

1. it could be nice to persist the warning if you navigate away from the input
2. supply a link to the documentation / theme name guidelines if a warning is issued

Regarding 1: 

Warning is shown | Warning disappears when you navigate away
--- | ---
<img width="1624" alt="Screenshot 2023-04-27 at 9 41 17 AM" src="https://user-images.githubusercontent.com/5375500/234880942-ef9cf25d-de2d-466c-9a84-a4d6d1df49e8.png"> | <img width="1624" alt="Screenshot 2023-04-27 at 9 41 19 AM" src="https://user-images.githubusercontent.com/5375500/234881046-b73e8fb1-1d0a-4980-bd66-91c66820cf75.png">

**Comment by pbking** [comment]
This UI has been depreciated and this issue no longer seems relevant.
