### ISSUE TITLE
Feature Request: Reset all user customizations

### ISSUE THREAD

**Issue by spacedragn** [WordPress/create-block-theme#344]
In addition to the 6 Generation options, I’d like to request a 7th: “Reset all user theme customizations” to call `clear_user_styles_customizations()` once without the other “Overwrite” functions.

[Long story short](https://wordpress.org/support/topic/feature-request-reset-all-user-customizations/), I needed to “Clear Customizations” to rectify some malformed code that was cached in the Editor and erroring out. But the usual dropdown didn’t detect any customizations and therefore wasn’t available. So I called this function in my theme once and it solved my problem.

A “Reset” option also saves time. Devs won’t have to drill through UI for every template and template part in their theme.

**Comment by creativecoder** [comment]
I think this option is now present in the "three dots" menu under Global Styles in the Site editor, as "Reset styles":

<img width="306" alt="image" src="https://github.com/WordPress/create-block-theme/assets/1699996/ac2464d0-a79e-4bdf-a4da-3be6808a8c43">
