### ISSUE TITLE
Exporting adds unexpected keys to theme.json

### ISSUE THREAD

**Issue by jffng** [WordPress/create-block-theme#345]
When a user makes a change to layout and the exports, some unexpected key:values are added to the theme.json. 

**To replicate**
- Activate a block theme like TT3
- Go to global styles and make a change to the global layout like editing the default content width
- Use CBT to export the theme
- Verify that many changes were made to theme.json beyond what you just changed

Here is is an example where the only change I made was to the default content width via the global styles UI, and then exported: https://github.com/WordPress/wordpress-develop/pull/4406/commits/5d958aff3f424236682b31093b855f03cb1a7681

This issue is related to #324. It likely extends beyond just layout and is more broadly related to how the theme.json data is merged.

**Comment by jasmussen** [comment]
I went ahead and opened https://github.com/WordPress/gutenberg/issues/50238 as it appears to be a core issue!

**Comment by carolinan** [comment]
Has this been solved? Can the issue be closed?

**Comment by mikachan** [comment]
Good spot, yes I believe this was fixed with https://github.com/WordPress/gutenberg/pull/50268. Closing!
