### ISSUE TITLE
Request: add GitHub repo URL to plugin description page

### ISSUE THREAD

**Issue by kaitohm** [WordPress/create-block-theme#350]
It took me a while to locate this GitHub repo to file a bug. It would be great if the repo URL could be found from [the plugin description page](https://wordpress.org/plugins/create-block-theme/) somewhere 🙇‍♂️

**Comment by mikachan** [comment]
Thanks for reporting! This should be covered by https://github.com/WordPress/create-block-theme/pull/351.
