### ISSUE TITLE
Create blank theme: Update the minimum WordPress version

### ISSUE THREAD

**Issue by carolinan** [WordPress/create-block-theme#355]
When you select the Create blank theme option, the minimum required WordPress version is set to 5.8.
The theme cannot be activated on WordPress 5.8 because it is missing an index.php file.

The requirement to include the index.php file was removed in WordPress 6.0, so I recommend increasing it to at least that version.

**Comment by matiasbenedetto** [comment]
thanks for reporting this. This should fix it: https://github.com/WordPress/create-block-theme/pull/356
