### ISSUE TITLE
Error with `$temp_file` sometimes not being a string

### ISSUE THREAD

**Issue by mikachan** [WordPress/create-block-theme#360]
It looks like `$temp_file` in [class-manage-fonts.php](https://github.com/WordPress/create-block-theme/blob/trunk/admin/class-manage-fonts.php#L222) can sometimes not be a string, so we should improve how this is handled. I've noticed this error when using the plugin in a WordPress Playground environment.

![image](https://github.com/WordPress/create-block-theme/assets/1645628/d3efe3fc-ee3c-4b52-bd12-1b41328f38fc)

To reproduce:

1. Spin up a WordPress Playground instance with the plugin installed ([example](https://playground.wordpress.net/?theme=twentytwentythree&plugin=gutenberg&plugin=create-block-theme&url=/wp-admin/index.php))
2. Go to Appearance -> Manage Theme Fonts -> Add Google font button
3. Select a Google font from the dropdown menu
4. Select a font variant from the list of fonts
5. Click the 'Add Google fonts to your theme' button
6. You should see the above error

Originally discussed here: https://github.com/WordPress/wordpress-playground/issues/276

**Comment by pbking** [comment]
a font-related bug that is no longer relevant.  closing.
