### ISSUE TITLE
Invalid Zip exported resulting into error.

### ISSUE THREAD

**Issue by nd0nd0** [WordPress/create-block-theme#371]
Currently running on local using Windows 11. 

When cloning a 2023 theme, an invalid zip is exported resulting in the `The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10): Unable to find End of Central Dir Record signature` error.

Much appreciated.

**Comment by ghost** [comment]
Similar to the error above. 
Running on Local using Windows 11.
 When using the Create Block Theme -creating a child theme of Frost, Received this error message
 
 Installing theme from uploaded file: frostchild.zip
Unpacking the package…
The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature 

When I try to open zip folder in file explorer it says there is nothing in the folder.
Any update on a way to fix this error. Thank you

**Comment by mikachan** [comment]
Thanks for reporting this. Could you please confirm if the latest version of the plugin fixes this issue? There's a potential fix in version 1.12.0. Thanks 🙇

**Comment by ghost** [comment]
It is magic. Yes, version 1.12.0 fixed the issue. Thank you

**Comment by mikachan** [comment]
Brilliant, thanks for letting us know! I'll close this, but please feel free to re-open if the issue happens again.
