### ISSUE TITLE
Consider not running cron GitHub Actions on forked repositories

### ISSUE THREAD

**Issue by t-hamano** [WordPress/create-block-theme#386]
As I understand it, [the GitHub Actions cron checks for Google Fonts updates](https://github.com/WordPress/create-block-theme/blob/b400afa3086d002c29221e3e388498fd64bcc9db/.github/workflows/update-google-fonts-data.yml#L9) every Tuesday and a pull request is created.

It seems that this cron runs even on forked repositories. And I am getting weekly notifications that the GitHub Actions have failed:

![gmail](https://github.com/WordPress/create-block-theme/assets/54422211/d9e6a254-4e8b-4f76-bb63-c7ed1f5e2cd1)

The results of failed GitHub Actions on a forked repository can be found [here](https://github.com/t-hamano/create-block-theme/actions).

This problem can probably be solved by changing the forked repository to not perform GitHub Actions:

![disable-actions](https://github.com/WordPress/create-block-theme/assets/54422211/b1238632-72e6-4a08-8254-0563e3f02d88)

However, I think it would make sense to add a setting in GitHub Actions itself to exclude forked repositories.

**Comment by matiasbenedetto** [comment]
Yes, it seems like a good idea to disable the "Update Google fonts" and "Deploy" actions. However, the "Run linter/format checks" is useful even on forked repos.

Apart from that, I'm not sure if there is a Github option to disable the action on forked repositories as you describe. At least I'm not seeing in my test repo:

![image](https://github.com/WordPress/create-block-theme/assets/1310626/89d54002-2197-406d-b8e9-c83d1deb73a5)

**Comment by vcanales** [comment]
I've created https://github.com/WordPress/create-block-theme/pull/391 as a proposal to only check for the repo owner on the Google Font update action, since as @matiasbenedetto mentions, the settings don't allow for this granular level of control.
