### ISSUE TITLE
Remove QueryId from the exported themes

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/create-block-theme#397]
Exported theme includes `QueryId` attribute in the template. It should be removed to avoid content issues when theme installed on other sites.

`<!-- wp:query {"queryId":14,"query":{"perPage":"6","pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"exclude","inherit":false},"displayLayout":{"type":"flex","columns":3},"layout":{"type":"constrained","wideSize":"1400px"}} -->`

**Comment by mikachan** [comment]
I believe that `queryId`s should be preserved, based on this discussion here: https://github.com/WordPress/wordpress-develop/pull/3899#discussion_r1104638014
