### ISSUE TITLE
Unable to download Child theme

### ISSUE THREAD

**Issue by ashsahibabad** [WordPress/create-block-theme#415]
Plugin: Create block theme

It gives me the NETWORK ISSUE when creating the child of greenshift theme? I've only four plugins installed...

**Comment by vcanales** [comment]
Hi! Could you provide more details about the problem you're having? Error messages and a link to the specific theme you mention would be helpful.

**Comment by ashsahibabad** [comment]
Can you send me the child theme of Greenshift theme?

**Comment by fxbodin** [comment]
I have also the Network Issue happening while downloading a sibling of the activated child theme. Tried with Chrome MacOS and Safari.

**Comment by colorful-tones** [comment]
I somewhat recall encountering this issue if Gutenberg plugin was not installed and activated. Does Create Block Theme still require the Gutenberg plugin? I assume not, because it does not mention in the README, but I feel like it did at one point. 🤷

**Comment by Marc-pi** [comment]
i do have the same issue, with and with no Gutenberg plugin active.
TT3 export, i even test with Chrome Security to OFF. The file should be 2.1Mo, maybe it is too big and needs to be generated first.

**Comment by LittleBigThing** [comment]
I have this issue as well (on a multisite installation, plugin activated only for the current site).

**Comment by LittleBigThing** [comment]
See also #207

**Comment by pbking** [comment]
Construction of a child theme workflow is different now and this doesn't seem relevant anymore.  Closing.  

Please re-open if the problem persists (even in the new workflow) and we'll look into it more deeply.
