### ISSUE TITLE
Create Block Theme 1.0.0 Release

### ISSUE THREAD

**Issue by pbking** [WordPress/create-block-theme#42]
For a 1.0.0 Release we will ensure that the plugin can do the following tasks:

### Export your existing block theme

With a non-child theme activated export your theme to a .zip file.  The theme.json in the exported package will include changes made via the FSE Global Styles editor.  Any customizations or additions to block templates or block template parts will be included in the exported package.

With a child theme activated export your theme to a .zip file.  The changes should be the same as an exported parent theme.

### Create a Child theme from the activated Theme

With a non-child theme activated create a new theme and export it to a .zip file.  The exported theme will have all of the changed made to templates and global styles.

### Clone a non-child theme

Create a new theme based on the current activated theme but with changes made to templates and global styles.   Limited resources will have namespaced resources refactored (such as function names in `functions.php`).

### Clone a child theme

Create a new theme based on the current activated theme but with changes made to templates and global styles.  (This is called a "sibling" theme).  Limited resources will have namespaced resources refactored (such as function names in `functions.php`). The resulting new theme will be a child of the same theme the currently activated theme is a child of.

**Comment by MaggieCabrera** [comment]
I think we've covered all this but we didn't bump the version. We should make a pass for bugs and then do the bump and update the plugin in the repo
