### ISSUE TITLE
Groups within header template-part ignores content-width toggled to on.

### ISSUE THREAD

**Issue by Ren2049** [WordPress/create-block-theme#420]
It does only happen in a blank theme created with the plugin (tested it in TT3 just now), I've opened an issue in the Gutenberg section with more details and a video: https://github.com/WordPress/gutenberg/issues/52657#issue-1806001671

There's also an alignment issue with a site icon and an image of a wordmark next to it when viewed on the front end.

Just specualting but does the TT3 theme use some kind of default CSS like a CSS reset which the blank theme lacks?

Btw. thanks for making this plugin!

**Comment by carolinan** [comment]
Hi
Thank you for the reports.

It is difficult for me to follow along, can I ask you to please create separate issues if there is more than one problem?

It would be helpful if you could include the following information:
WordPress version
Create block theme version
If Gutenberg is active or not, and which version
Did you deactivate all other plugins?

You wrote that you used the blank theme option. Did you make any other changes than adding a new content width?
And you added the content width through the Site Editor Styles sidebar? Or did you make the change in theme.json?

TT3 does not use any additional CSS reset, the block editor does have one, but that is used independently of the active theme.

**Comment by Ren2049** [comment]
I'm closing this because your tip with the full width setting in the other issue solved it basically, thanks again!
