### ISSUE TITLE
Refactor Namespaced Resources

### ISSUE THREAD

**Issue by pbking** [WordPress/create-block-theme#43]
When CLONING a PARENT or creating a SIBLING theme (cloning a child theme) the resulting resources could be namespaced.

For example functions like this:
```
function twentytwentytwo_support() {
```
should be refactored to:
```
function my_new_theme_support() {
```
and 
```
wp_register_style('twentytwentytwo-style',...
```
to
```
wp_register_style('my-new-theme-style',...
```

We should consider the following resources when refactoring the namespace:
```
functions.php
??? what else ???
```

**Comment by MaggieCabrera** [comment]
The textdomain for all translated strings should match what's on the style.css file. I bet there's a regex for that somewhere.
Block patterns inserted on a template may also be targeting the original theme name.

**Comment by pbking** [comment]
I believe this is all done and ready for review now.

**Comment by pbking** [comment]
@jffng pointed out some gaps in this change in #5694 where a number of comments referencing the original Theme Name were not refactored.  We should address that before bringing in.

**Comment by pbking** [comment]
> @jffng pointed out some gaps in this change in #5694 where a number of comments referencing the original Theme Name were not refactored. We should address that before bringing in.

[Done](https://github.com/Automattic/create-block-theme/pull/52/commits/e5d7d8b571a695c4cdde6b0f7de004e224f7f9a9).
