### ISSUE TITLE
Blank theme CSS causes Site Logo block misalignment in the browser when set to link to home

### ISSUE THREAD

**Issue by Ren2049** [WordPress/create-block-theme#432]
The site logo block in the blank theme doesn't inherit line-height: 0 when set to link to home in the editor. This causes a misalignment where additional padding gets added to the bottom of the site logo as you can see in the second image. 

Here's the CSS with TT3:

![tt3](https://github.com/WordPress/create-block-theme/assets/133038357/2785a20e-26f8-4e3b-b024-259ba6ec3bb9)

Here the blank theme, as you can see the box surrounding the logo got bumped by 10px to 40x50 instead of 40x40 like in TT3 which is causing the misalignment:

![blank-theme](https://github.com/WordPress/create-block-theme/assets/133038357/3c3e26f6-7694-46f1-a2a4-4334005164fb)

Tested in a local install on a Mac, Firefox browser, WP 6.3 RC2, no plugins enabled except the beta and create block theme plugins.

**Comment by t-hamano** [comment]
Thanks for the report. This is a Gutenberg issue and I believe [this PR](https://github.com/WordPress/gutenberg/pull/53909) will solve this problem.

**Comment by Ren2049** [comment]
Allright, gonna close this one for now.
