### ISSUE TITLE
Deprecated Functions

### ISSUE THREAD

**Issue by kafleg** [WordPress/create-block-theme#442]
WP: 6.3 
PHP: 8.1 

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in C:\laragon\www\paidreviews\wp-includes\functions.php on line 7127

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\laragon\www\paidreviews\wp-includes\functions.php on line 2182

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in C:\laragon\www\paidreviews\wp-includes\functions.php on line 7127

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\laragon\www\paidreviews\wp-includes\functions.php on line 2182

**Comment by kafleg** [comment]
Tested Github version and found this, 

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in C:\laragon\www\paidreviews\wp-includes\functions.php on line 7127

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\laragon\www\paidreviews\wp-includes\functions.php on line 2182

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in C:\laragon\www\paidreviews\wp-includes\functions.php on line 7127

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\laragon\www\paidreviews\wp-includes\functions.php on line 2182

Warning: include(C:\laragon\www\paidreviews\wp-content\plugins\create-block-theme/build/wp-org-theme-directory.asset.php): Failed to open stream: No such file or directory in C:\laragon\www\paidreviews\wp-content\plugins\create-block-theme\admin\wp-org-theme-directory.php on line 50

Warning: include(): Failed opening 'C:\laragon\www\paidreviews\wp-content\plugins\create-block-theme/build/wp-org-theme-directory.asset.php' for inclusion (include_path='.;C:/laragon/etc/php/pear') in C:\laragon\www\paidreviews\wp-content\plugins\create-block-theme\admin\wp-org-theme-directory.php on line 50

Warning: Trying to access array offset on value of type bool in C:\laragon\www\paidreviews\wp-content\plugins\create-block-theme\admin\wp-org-theme-directory.php on line 55

Warning: Trying to access array offset on value of type bool in C:\laragon\www\paidreviews\wp-content\plugins\create-block-theme\admin\wp-org-theme-directory.php on line 56

**Comment by t-hamano** [comment]
Thank for the report. This issue looks similar to https://github.com/WordPress/create-block-theme/issues/168.

**Comment by vcanales** [comment]
Fixed in https://github.com/WordPress/create-block-theme/pull/462
