### ISSUE TITLE
PHP Required >= 7.4

### ISSUE THREAD

**Issue by dd32** [WordPress/create-block-theme#444]
The plugins readme.txt has `Requires PHP: 7.0` but currently the plugin requires PHP 7.4 or higher.

On PHP 7.3 the following error is triggered: [(support thread)](https://wordpress.org/support/topic/fatal-error-when-plugin-activated-5/)
> Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /wordpress/wp-content/plugins/create-block-theme/admin/create-theme/cbt-zip-archive.php on line 8

On PHP 5.6, 7.0, 7.1, and 7.2 the following error is triggered:
> Parse error: syntax error, unexpected ')' in /wordpress/wp-content/plugins/create-block-theme/admin/class-create-theme.php on line 52

Note: I've tested this using https://playground.wordpress.net/?plugin=create-block-theme&php=7.3&wp=6.2&storage=temporary

_I've temporarily overridden the `Requires PHP` version on wordpress.org/plugins for this plugin to 7.4, upon next update it'll revert to the value in readme.txt_

**Comment by kafleg** [comment]
https://github.com/WordPress/create-block-theme/pull/445
