### ISSUE TITLE
Add "Save" option

### ISSUE THREAD

**Issue by pbking** [WordPress/create-block-theme#45]
Perhaps we could consider a "save" option for the theme.  If the current option exports a .zip an additional option could be to "save" the theme where the changes get stored in the theme folder rather than exported as a .zip file.

This would allow the development experience of themes to happen in the FSE and be updated in what is my development environment allowing me to skip the export/unpack/copy/delete process that happens whenever I export the theme.

**Comment by MaggieCabrera** [comment]
I think this is being discussed to add on core right now too
