### ISSUE TITLE
Call to undefined method WP_Error::addThemeDir() 

### ISSUE THREAD

**Issue by tcope25** [WordPress/create-block-theme#452]
Anytime I hit the Generate button, no matter the selection, I get this error:

_There has been a critical error on this website. Please check your site admin email inbox for instructions._

**Logs**:

2023-09-06 20:36:45.690140 [NOTICE] [590851] [*:46043-Q:4067339A715A8AE4-44#*.com] [STDERR] PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::addThemeDir() in /home/*.com/public_html/wp-content/plugins/create-block-theme/admin/create-theme/theme-zip.php:103
Stack trace:
#0 /home/*.com/public_html/wp-content/plugins/create-block-theme/admin/class-create-theme.php(260): Theme_Zip::add_templates_to_zip()
#1 /home/*.com/public_html/wp-content/plugins/create-block-theme/admin/class-create-theme.php(464): Create_Block_Theme_Admin->create_child_theme()
#2 /home/*.com/public_html/wp-includes/class-wp-hook.php(310): Create_Block_Theme_Admin->blockbase_save_theme()
#3 /home/*.com/public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#4 /home/*.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /home/*.com/public_html/wp-admin/admin.php(175): do_action()
#6 /home/*.com/public_html/wp-admin/themes.php(10): require_once('...')
#7 {main}
  thrown in /home/*.com/public_html/wp-content/plugins/create-block-theme/admin/create-theme/theme-zip.php on line 103

Wordpress 6.3.1
PHP Version 8.0.27

**Comment by mikachan** [comment]
I can't replicate this using WordPress 6.3.1 and PHP 8.0.27. I'm wondering if this could be an issue related to your hosting environment. Could you please check if you have access to the ZipArchive class on your server? You may need to contact your hosting provider, or you can try these further instructions to enable ZipArchive in [this article](https://wpthinker.com/enable-zip-archive-in-wordpress/).

**Comment by tcope25** [comment]
You were right. ZipArchive wasn't enabled. After adding the extension to php.ini it worked.

**Comment by mikachan** [comment]
Brilliant, so glad that worked! Thanks for reporting back ✨ I'll close this issue.
