### ISSUE TITLE
No changelog for v1.13.3

### ISSUE THREAD

**Issue by jordesign** [WordPress/create-block-theme#463]
The readme.txt has no entries in the changelog for v1.13.3 - to know what changes have taken place.

**Comment by vcanales** [comment]
Weird, the changelog is present [on the release](https://github.com/WordPress/create-block-theme/releases/tag/v1.13.3) but it wasn't added to the readme.txt file. I'll make a note of checking why this may have happened, on the next release. For now, I'll clean up and add the changes manually.
