### ISSUE TITLE
Plugin fails with critical error when Gutenberg not enabled

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/create-block-theme#48]
#### Steps:

* Disable Gutenberg
* Create block theme

<img width="593" alt="image" src="https://user-images.githubusercontent.com/1935113/156759108-7412c91a-a88c-4b2f-b8fb-a8c89535422e.png">

#### Expected result

Disable/remove the option when Gutenberg is not enabled.

**Comment by beebeegit** [comment]
I have probably the same issue. 
WordPress 6.0, Theme Skatepark, on localwp (by flywheel)
![Error-Message-01-06-2022](https://user-images.githubusercontent.com/60343816/171471214-002c7fc9-d83c-423d-8910-b106dab22756.jpg)
![class-create-block-theme-admin php](https://user-images.githubusercontent.com/60343816/171471298-111dc52a-b800-498a-87c8-2e487849b0f6.jpg)

**Comment by pbking** [comment]
I don't believe we will need to remove the option when Gutenberg is not activated, but instead leverage the logic from core.  Versions < 6.0 (without Gutenberg) will probably not be supportable though.

**Comment by beebeegit** [comment]
As I use WP 6.0 does that mean I have to install the Gutenberg plugin anyway? I thought this is redundant in 6.0.

**Comment by pbking** [comment]
WP 6 Core provides some of the functionality of Gutenberg but sometimes in differently named functions.  The target or this plugin is to work with WP 6.0 but that transition hasn't happened yet.  At the MOMENT using Gutenberg is necessary, but we're working on fixing that.

**Comment by beebeegit** [comment]
Thanks. Good to know. With Gutenberg installed it worked fine.
