### ISSUE TITLE
"Manage theme fonts" page title overrides the title on other admin pages, including pages from other plugins

### ISSUE THREAD

**Issue by carolinan** [WordPress/create-block-theme#483]
When Create Block Theme is active at the same time as some other plugins, the sub page title "Manage theme fonts" is overriding the title of other admin pages.

Plugins affected by this bug are for example:
Yoast SEO
Jetpack
Site Kit

Because of the negative impact this has on other plugins, I have added the high priority label.

### To reproduce:
Activate a block theme
Activate Create Block Theme plugin
Activate Jetpack

In the WordPress admin area, in the sidebar menu below "Dashboard", click on "Jetpack".
Confirm that the page title is incorrect.

![Screenshot of the Jetpack plugin page with incorrect page title](https://github.com/WordPress/create-block-theme/assets/7422055/de367ec3-0291-4584-8f00-ab9a8e87cc17)

**Comment by bacoords** [comment]
Noting that I can replicate this bug as well. Perhaps due to the `$title` global being overridden: https://github.com/WordPress/create-block-theme/blob/6208be768b81bf5b656a7546aa015489c2099278/admin/class-manage-fonts.php#L45

**Comment by bacoords** [comment]
Update - looks like there is a merged PR for this: https://github.com/WordPress/create-block-theme/pull/479

**Comment by vcanales** [comment]
> Update - looks like there is a merged PR for this: #479

Exactly, but haven't released a new version yet; we'll do that shortly. Thanks for the report!

**Comment by carolinan** [comment]
Excellent, thank you!
