### ISSUE TITLE
Bug: Manage Theme Fonts page does not load in v1.13.5

### ISSUE THREAD

**Issue by unscripted** [WordPress/create-block-theme#486]
## Issue

A breaking change was introduced in v1.13.5 that prevents the Manage Theme Fonts page from loading.

The console outputs two instances of the following error.

ReferenceError: __ is not defined

Note: I could roll back to v1.13.4, and the page loads as expected.

## Steps to reproduce

- Update create-block-theme plugin to v1.13.5.
- Navigate to Appearance > Manage Theme Fonts.
- See a white screen in the `wpbody` div.

**Comment by vcanales** [comment]
Fixed in https://github.com/WordPress/create-block-theme/pull/485
