### ISSUE TITLE
Patternize + Escape templates with strings

### ISSUE THREAD

**Issue by jffng** [WordPress/create-block-theme#489]
**Background**
Currently, only templates with images are transformed to patterns. In this process, the image is made "local" to the theme, as well as strings get escaped and marked for translation. 

https://github.com/WordPress/create-block-theme/blob/017d52004e46d6c2ab38e68ef1be2bc08922fb2f/admin/create-theme/theme-zip.php#L114C44-L130

**Proposal**
It could be useful to allow all templates that contain strings, to follow the same behavior — transformed to a pattern and strings escaped + marked for translation.

**Comment by pbking** [comment]
Consider including the user to make this optional.

A setting?  A Prompt? A separate "saving" button?

**Comment by alaczek** [comment]
Could we fast-track this issue? Creating patterns and making strings translatable is the majority of manual labor after generating a theme atm, and would go a long way to speeding up our process.

> A setting? A Prompt? A separate "saving" button?

Could this be an option on this screen (for Clone specifically)?

<img width="1506" alt="image" src="https://github.com/WordPress/create-block-theme/assets/4550351/3c772843-df57-4b2c-9e83-312ef1ce4ee8">

**Comment by pbking** [comment]
We actually have a branch for this work that should be coming in... today?  Soon at least.

It's done automatically, and might not cover all situations yet but it's a beginning.  It isn't optional currently, but that's an idea that's been considered.

Planned for an upcoming release of CBT in the next week or two.
