### ISSUE TITLE
"Adding Google Fonts" is blocked by WP

### ISSUE THREAD

**Issue by V6938** [WordPress/create-block-theme#490]
Hello,

I created a test website with WP, from scratch, and added "Create Block Theme".
When I attempt to add any google font, the system answers :
"Erreur : `DISALLOW_FILE_EDIT` ne peut pas être activé dans wp-config.php pour faire des modifications du thème en utilisant cette extension."
which means, in English 
 "Error: `DISALLOW_FILE_EDIT` cannot be enabled in wp-config.php to make theme edits using this extension."

Adding in wp-config.php the line
define( 'DISALLOW_FILE_EDIT', false );
doesn't change anything

I use WP6.4.2 / PHP 7.4 / the default theme "twenty twenty four"
Has anyone of you met and fixed this error ?

Thank you for your attention

**Comment by creativecoder** [comment]
Hi @V6938 , it looks like the plugin is detecting that `DISALLOW_FILE_EDIT` is defined as `true` somewhere in your site configuration, which will prevent you from updating theme files using the plugin.

**Comment by V6938** [comment]
Hi @creativecoder , Thanks for your help !
I first tried to place the string  "define( 'DISALLOW_FILE_EDIT', false );" at the very end of the file.
I moved it somewhere else in the wp-config.php, which made it work.
For future readers it looks like this in my file :

...(other code before)...
if ( ! defined( 'WP_DEBUG' ) ) {
	define( 'WP_DEBUG', false );
}

define( 'DISALLOW_FILE_EDIT', false );
... other code follows

**Comment by creativecoder** [comment]
@V6938 Glad you got it working! I'll go ahead and close this issue.
