### ISSUE TITLE
Font Manager: integrate with WordPress Font Library

### ISSUE THREAD

**Issue by creativecoder** [WordPress/create-block-theme#493]
How should the Create Block Theme Font Manager integrate with the WordPress Font Library feature? They serve a very similar purpose, but slightly different purpose.

I'd propose:

- Remove the Font Manager section of Create Block Theme, in favor of using the WordPress Font Library
- On theme export, or when styles are saved to theme files, active fonts should have font files exported to the theme and theme.json `fontFace` `src` properties updated to be file paths relative to the theme.

**Comment by pbking** [comment]
Duplicate of #451
