### ISSUE TITLE
Ability to reset theme style settings

### ISSUE THREAD

**Issue by creativecoder** [WordPress/create-block-theme#494]
## What problem does this address?

A common workflow for updating theme settings using Create Block Theme is

1. Load an existing base theme (Twenty Twenty Four is currently a common choice)
2. Edit Global Styles
3. Persist those to theme.json, using Create Block theme
4. Export the theme files

One thing you can't do in this workflow (without manually editing theme.json) is to reset or remove a theme's styles, without overriding them.

We should have a way to do this in the UI, at least through [a theme.json editor](https://github.com/WordPress/create-block-theme/issues/491), but ideally in the Global Styles UI.

**Comment by creativecoder** [comment]
Related to https://github.com/WordPress/create-block-theme/issues/466

**Comment by annezazu** [comment]
Agreed that this makes more sense to explore in CBT plugin for now. Thank you for creating this issue here!
