### ISSUE TITLE
Theme exporting: improve tags interface

### ISSUE THREAD

**Issue by creativecoder** [WordPress/create-block-theme#495]
When exporting a theme, the theme tags section inherits whatever tags are being used in the base theme.

<img width="1057" alt="image" src="https://github.com/WordPress/create-block-theme/assets/1699996/963d617a-205c-4cee-82f4-b838605f5da9">

These could use some improvements, for starters

- A "Deselect all" option, so you can easily remove the base theme tags
- A better description that tells these are important/useful

**Comment by matiasbenedetto** [comment]
This issue references a deprecated UI, so I'm closing this issue as not planned.
