### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by t-hamano** [WordPress/create-block-theme#507]
- This plugin requires WordPress 6.0 or higher and PHP version 7.4 or higher. If we use the GitHub Actions matrix to test all combinations, we can ensure that they work correctly on all WordPress/PHP versions and catch problems with specific versions in advance.
- e2e testing expects "this is how it should work." Therefore, it is useful for clarifying specifications.
- When a PR is submitted, it is guaranteed that it will not introduce new issues or regressions.
- The `@wordpress/scripts` package now supports Playwright testing, so adding e2e testing shouldn't be difficult.
- The Gutenberg project has moved most of its E2E tests to Playwright. There is a wealth of information out there to help us understand what code to write to do what we need.

**Comment by pbking** [comment]
We have recently fleshed out integration testing.  I don't believe there is much value in additional E2E testing.  We should continue to expand our integration testing to ensure that what is exported/saved, etc is what is expected.  But testing the UI to do this doesn't add value.  I suggest we close this.

**Comment by t-hamano** [comment]
I see, let's close this issue for now 👍
