### ISSUE TITLE
Make sure patch version gets removed when theme is exported

### ISSUE THREAD

**Issue by iamtakashi** [WordPress/create-block-theme#523]
> RECOMMENDED: Tested up to is recommended to have major versions only (e.g. 5.8). Patch version is not needed (e.g. 5.8.1).

When I run the theme check, this often comes up. Let's make sure it gets removed when the theme is exported. It seems to be low-hanging fruit that will save us time!

**Comment by pbking** [comment]
I don't believe that we should be automatically removing the patch version.  It's recommended, though not enforced and the Automattic theme workflow still depends on patch versioning.

The Metadata editor allows for the version to be changed.  It's not automated, but you can remove the patch version in that way.

I do believe that the patch version can be excluded when creating/cloning a theme though.

**Comment by mikachan** [comment]
I believe this issue is in reference to the "Tested up to" WordPress version number, not the theme version number.

**Comment by pbking** [comment]
Ahhh

Silly. Of course. 

In that case, yrs of course!
