### ISSUE TITLE
Font licenses are no longer automated with new Core Font Library functionality

### ISSUE THREAD

**Issue by mikachan** [WordPress/create-block-theme#525]
Part of replacing the integrated font management with the new Font LIbrary in Core means that we're losing the automated font license functionality provided by this plugin.

This is currently handled with the `manage_font_license()` function, included [here](https://github.com/WordPress/create-block-theme/blob/trunk/admin/class-manage-fonts.php#L335).

Perhaps this could be added as a follow-up to https://github.com/WordPress/create-block-theme/pull/518 and https://github.com/WordPress/create-block-theme/pull/519.

**Comment by matiasbenedetto** [comment]
I'm working on a fix for this. I will submit the PR once this work gets merged: https://github.com/WordPress/create-block-theme/pull/626

**Comment by pbking** [comment]
Fixed with #649
Closing
