### ISSUE TITLE
Preset user with options before overriding theme changes with "save changes"

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/create-block-theme#535]
Add options to "save changes" menu to ask user with following choices.

* Save global styles as theme.json
* Remove refs from navigation menu
* remove image references
* more..

<img width="281" alt="image" src="https://github.com/WordPress/create-block-theme/assets/1935113/fe7a1fd0-e949-47a8-be81-bff4842f113f">

**Comment by pbking** [comment]
Ooh, I was wondering how we might achieve this, and I think this is a good idea!  Easy to implement and understand.
