### ISSUE TITLE
Create theme UI is confusing with single form and many submit buttons

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/create-block-theme#538]
Create Theme form is bit confusing with single form with too many submit buttons which feels disconnected.

<img width="285" alt="image" src="https://github.com/WordPress/create-block-theme/assets/1935113/2e9f42cd-f480-47ea-9b27-77418abc442f">
<img width="284" alt="image" src="https://github.com/WordPress/create-block-theme/assets/1935113/21f58592-2937-4027-9741-ea62975dd443">

For example, to create a variation, there is no need of all the information from the form. When trying to create a duplicate variation, it simply throws a message "Variation already exists", there is no clue as to what went wrong.

Preset with a better user experience and ask only relevant information for the given choice.

**Comment by mikachan** [comment]
I agree, it's not clear how these buttons are related to the form above them. Maybe we could split each option into its own panel, and then each one would have its own form.

**Comment by madhusudhand** [comment]
Attaching one of earlier ideas for inspiration. Options in the editor can be split into the similar style.

![cbt-ui](https://github.com/WordPress/create-block-theme/assets/1935113/582a8a3c-97c3-4f64-be65-9e6d049ed9f6)
