### ISSUE TITLE
v2 Update Errors/Warnings

### ISSUE THREAD

**Issue by jbodnar2** [WordPress/create-block-theme#549]
`Failed to open stream: No such file or directory in /.../wp-content/plugins/create-block-theme/admin/wp-org-theme-directory.php on line 54`

Which is 

```
function assets_enqueue() {
  $asset_file = include( plugin_dir_path( dirname( __FILE__ ) ) . 'build/wp-org-theme-directory.asset.php' );
```

**Comment by vcanales** [comment]
We've released 2.0.2 with a fix to this issue, please update and try again
