### ISSUE TITLE
Update v2.0 Makes the Manage Fonts Go Blank

### ISSUE THREAD

**Issue by divisa-developer** [WordPress/create-block-theme#550]
As the title says, I did nothing but update the plugin and now I can’t see anything when the page manage-fonts loads, I see in the console that is trying to load a .js and .css files that no longer exists (under the directory /wp-content/plugins/create-block-theme/build). The fonts seem to be working properly despite that. It happened in two sites with different plugins installed so I’m inclined to believe it’s the update that broke the management of fonts. Is there anything else I should do after the update?

**Comment by vcanales** [comment]
We've released 2.0.2 with a fix to this issue; please update to that version and try again

**Comment by divisa-developer** [comment]
> We've released 2.0.2 with a fix to this issue; please update to that version and try again

Thank you kindly for the quick response
