### ISSUE TITLE
Include Documentation on wp-admin Page

### ISSUE THREAD

**Issue by pbking** [WordPress/create-block-theme#556]
Currently the wp-admin page has a depreciated form for the creation of a theme.  This is expected to be removed in the next minor version of Create Block Theme.

In it's place will include documentation that describes what CBT can do and how to do it.

* Outline the workflows that should be represented in this documentation.
* Provide screenshots of these workflows
* Provide copy that describes the workflow.
* Determine the design of how this documentation should be presented. (Consider that additional tools like a simple 'Getting Started' wizard, an export button or a "Create Blank Theme" type of utilities might also be offered in this space).

**Comment by justintadlock** [comment]
Just copying over the workflows that we had [discussed earlier](https://docs.google.com/document/d/1w2a6zKWnfVSznTrdmOqBh45ExWUo-ngz5pkSSVfTloA/edit?usp=sharing):

- Create a Blank Theme
- Manage Fonts in a Theme
- Clone existing theme and make it your own
- Save a Style Variation
- Make changes to an existing theme styles & templates
- Make changes to an existing theme metadata
- Export your theme as a .zip (without user changes)
- Export your theme as a .zip (with user changes)

**Comment by mikachan** [comment]
I believe this can be closed now that https://github.com/WordPress/create-block-theme/pull/637 has landed.
