### ISSUE TITLE
Font library management no longer stores font in theme folder on theme export

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/create-block-theme#558]
Since version 2.0 exporting fonts no longer stores the font files inside the theme. Instead, the theme references the fonts in the `uploads` directory. 

This is an issue because the fonts are not managed in git / shared across environments.

It would be great to get back the previous handling where font files were moved to the theme folder when exporting :)

**Comment by pbking** [comment]
This functionality is available when a theme is SAVED with CBT  however you're right that it doesn't handle this when it's exported without saving. 

We'll get that added. However in the meantime you should be able to save the theme and the font assets will be stored in it and referenced correctly when exported after that.
