### ISSUE TITLE
Name a style variation when creating in the Site editor

### ISSUE THREAD

**Issue by creativecoder** [WordPress/create-block-theme#559]
From https://wordpress.org/support/topic/saving-new-style-variation/

> The option to save changes to a Style Variation from the site editor no longer allows you to give the variant a name. The previous option list from the Appearance dashboard did give that option.
> 
> Please don’t forget to add that back in before the dashboard options settings are deprecated!

**Comment by pbking** [comment]
The option to name the variant is available... it just is very confusing. :P 

You name the "theme" on the form and then click the "Create Theme Variation" button.  The name given there will be used.

This will hopefully be addressed my cleaning up the interface.  Work on that is being done here: https://github.com/WordPress/create-block-theme/issues/538
