### ISSUE TITLE
Add ability to change screenshot of theme from editor tools

### ISSUE THREAD

**Issue by pbking** [WordPress/create-block-theme#560]
The screenshot can be provided from the wp-admin interface but not from the editor interface.  This should be added.

**Comment by t-hamano** [comment]
I tried creating a mockup, what do you think? The code can be found [here](https://github.com/WordPress/create-block-theme/blob/4e733f6695b2b0f9d0844d067722bd1286a5b3ef/src/editor-sidebar/metadata-editor-modal.js#L213-L278) on the [metadata-screenshot](https://github.com/WordPress/create-block-theme/tree/metadata-screenshot) branch.

![image](https://github.com/WordPress/create-block-theme/assets/54422211/5cc658ee-11f5-41a0-b594-f116929298f7)

**Comment by pbking** [comment]
That was a great start @t-hamano thank you!

I continued some work on that branch.  Interested in your thoughts on the bits I added.
