### ISSUE TITLE
Cloning a theme causes critical error

### ISSUE THREAD

**Issue by mikachan** [WordPress/create-block-theme#566]
Cloning a theme seems to cause a critical error:

`Parse error: syntax error, unexpected token "-", expecting "(" in /Users/sarahnorris/Source/Automattic/a8c-projects/themes/tt4-2/functions.php on line 22`

![image](https://github.com/WordPress/create-block-theme/assets/1645628/5ee11050-91b5-41bf-ac29-b60ccbecd5f6)

You do not need to make any changes to the theme - just attempting to clone seems to reproduce the error. I've tested this with Twenty Twenty-Four and Programme.

Originally mentioned on Slack here: https://wordpress.slack.com/archives/C015GUFFC00/p1712938209077399

**Comment by askdesign** [comment]
Thanks for following up with testing and the posting of this issue @mikachan
