### ISSUE TITLE
Add section to contribute to the readme file. 

### ISSUE THREAD

**Issue by bph** [WordPress/create-block-theme#581]
Could be a third item under FAQ 

## How to contribute? 
Besides the Support forum, you can also [create a new issue](https://github.com/WordPress/create-block-theme/issues/new) on the GitHub repo. If you want to contribute code, feel free to [submit a PR on the GitHub repo](https://github.com/WordPress/create-block-theme/).

**Comment by t-hamano** [comment]
#614 added a section for contributions, so I'd like to close this issue.
