### ISSUE TITLE
Error saving theme due to `turn_off_reject_unsafe_urls()`

### ISSUE THREAD

**Issue by pbking** [WordPress/create-block-theme#584]
```
Fatal error: Cannot redeclare alt_turn_off_reject_unsafe_urls() (previously declared in /home/my/website.com/wp-content/plugins/create-block-theme/admin/create-theme/theme-media.php:101) in /home/my/website.com/wp-content/plugins/create-block-theme/admin/create-theme/theme-media.php on line 101
```

Originally reported [here](https://wordpress.org/support/topic/cannot-redeclare-turn_off_reject_unsafe_urls-in-theme-media-php101/).

**Comment by skorasaurus** [comment]
Can confirm that I am receiving this error message on 2.0.2; when I attempt to save my user changes. 

I had previously had 2.1.0 installed but had to roll back because of https://github.com/WordPress/create-block-theme/issues/585
