### ISSUE TITLE
Improve 'Save Changes' panel with persisted options or a "select all" option.

### ISSUE THREAD

**Issue by mikachan** [WordPress/create-block-theme#597]
The new "Save Changes" options give the end user much more control over how a theme is saved and finally exported. To help serve most users in the best possible way, some items are not selected by default:

![image](https://github.com/WordPress/create-block-theme/assets/1645628/ebf0b76c-c3f6-4663-ad14-4bff0e5907b5)

On the other hand, some users will want these options on every save. Should we consider adding a "select all" checkbox for these options to save some clicks here?

**Comment by pbking** [comment]
I think we might also want to consider persisting those selections instead.  More than regularly selecting all of them, I think users will probably most often have a preferred collection of options (always save all, never localize text, always localize images, never remove navigation refs).

Right now we give them the same starting point every time.

**Comment by mikachan** [comment]
> I think we might also want to consider persisting those selections instead.

Yeah agreed, I thought this might be a good way to handle this too.
