### ISSUE TITLE
Reset the theme version number to 1.0.0 when cloning a theme

### ISSUE THREAD

**Issue by mikachan** [WordPress/create-block-theme#613]
Mentioned by @iamtakashi:

> shouldn’t the version number start with 1.0.0 instead of the same as the base theme?

![image](https://github.com/WordPress/create-block-theme/assets/1645628/52456890-3b3b-4b54-9cec-b7a9636dbdbb)

**Comment by pbking** [comment]
Yes, definitely.  Also related to #570 which should be clearing the changelog when cloning as well.
