### ISSUE TITLE
Add image credits to the 'Edit Metadata' editor modal.

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/create-block-theme#615]
## What?
The deprecated admin page has a field to add image credits to the theme readme.txt file.

![image](https://github.com/WordPress/create-block-theme/assets/1310626/0c8d0ce8-734f-411c-9ef8-efe26a081776)

The site editor modal  'Edit Metadata' doesn't have it.

![Screenshot from 2024-05-03 17-08-56](https://github.com/WordPress/create-block-theme/assets/1310626/81165269-5cae-401e-81f0-85bc2151ec4e)

## Expected
It seems like the Image credits field should be added to the modal.

**Comment by t-hamano** [comment]
I made a simple mockup, what do you think? You can check the branch on [metadata-image-credits](https://github.com/WordPress/create-block-theme/tree/metadata-image-credits) and the code on e9ac753.

https://github.com/WordPress/create-block-theme/assets/54422211/f94764b0-e4b0-4201-890d-9994d48683c9

This mockup has separated the title, license type, and source URL into separate fields, but there may be two problems:

- Users may wish to add information other than these three.
- On deprecated admin pages, this field is a textarea. Therefore, it is difficult to parse that text and sort it into title, license type, and source URL.

Is it simply better to use a textarea?

**Comment by matiasbenedetto** [comment]
The mockup looks good and could be useful for creating new themes. Still, it adds an extra parsing complexity in case we want to load the existing readme.txt info from existing themes into the 'edit metadata' modal (https://github.com/WordPress/create-block-theme/issues/631), which I think could be a nice follow-up of https://github.com/WordPress/create-block-theme/pull/626.

It's not likely that all the themes with image credits have image credits in a uniform format, making it easy to parse to identify 'title,' 'license', and 'source URL' elements. Maybe we can this UI when the content of Image Credits is parsed as expected and and use the textarea as a fallback in cases where the content cannot be parsed.

**Comment by pbking** [comment]
> Is it simply better to use a textarea?

Yes, I think that it would be better to just use a textarea.  As @matiasbenedetto mentioned there's no way to know that the format of existing image credits are in.  Better to just give users a block to edit.
