### ISSUE TITLE
Cloned themes don't update the custom data added in the sidebar form

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/create-block-theme#625]
## What?
Cloned themes don't update the custom data added in the sidebar form

## Expected result
Add the data included in the form to `style.css` and `readme.txt`

![image](https://github.com/WordPress/create-block-theme/assets/1310626/8484b5a2-dbcf-43e1-af61-bb61cf469649)

## Screencast current result:

[Screencast from 09-05-24 16:00:46.webm](https://github.com/WordPress/create-block-theme/assets/1310626/16677882-9678-4d2c-b32b-4dd252c54a0b)

**Comment by pbking** [comment]
I wasn't able to reproduce this.  When I cloned, created a child theme or created a blank theme the metadata matched what I put into the form.

Maybe this has recently been addressed with recent changes?

**Comment by jffng** [comment]
I just tested this also, and the metadata is updated in the cloned theme.
