### ISSUE TITLE
Load data from readme.txt in the 'Edit metadata' modal

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/create-block-theme#631]
## What?
Currently, the 'Edit metadata' modal loads only some existing theme data items (such as 'Theme description', 'Author', 'Version', etc.) when you open it. Still, other existing data points coming from readme.txt (such as 'Recommended plugins' and 'Image Credtis') are not loaded, so they can not be edited but only overwritten with new content. Apart from that, it is not clear if you are editing or simply adding new data to the existing one.

![Screenshot 2024-05-13 at 10-15-59 Blog Home ‹ Template ‹ WP1 ‹ Editor — WordPress](https://github.com/WordPress/create-block-theme/assets/1310626/574a7d54-6a1e-46d0-8b25-2d5bdf4c96a0)

## Expected
Load data from readme.txt in the 'Edit metadata' modal so the theme creators can:
- Edit the existing data for 'Recommended plugins' and 'Image Credits'.
- Know the content of the readme.txt file without the need to inspect it in the filesystem as a text file.

**Comment by pbking** [comment]
Recommended plugins is loading and saving as expected (I can't recall in which branch it was fixed, but I think it was a side effect of another feature).
Font Credits are being added in this PR (#649)
I think the only thing mentioned that remains is adding Image Credits which is represented in [this issue](https://github.com/WordPress/create-block-theme/issues/615).  

Perhaps we could close this?

**Comment by matiasbenedetto** [comment]
Closing as completed by various PRs already merged.
