### ISSUE TITLE
Override option on child theme overrides child theme changes and user changes on parent theme

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/create-block-theme#64]
#### Steps:

* Activate a child theme such as `Quadrat` and use override option and export theme.
* Observe that it overrides parent theme `blockbase`

<img width="412" alt="image" src="https://user-images.githubusercontent.com/1935113/172301427-74401616-14dd-4a02-b472-c76c2e0071b2.png">

**Comment by robglidden** [comment]
I experience the same issue.

I created a new template in a child theme.

When I saved the child theme, the new template appeared in the parent theme.
