### ISSUE TITLE
Creating child theme isn't configured properly

### ISSUE THREAD

**Issue by bluebee-team** [WordPress/create-block-theme#644]
When using Create Block Theme using the "Create Child Theme of [Parent]" function, the resulting child theme isn't in a usable state. Use the Twenty Twenty Four theme as an example, when creating a child of it the resulting child theme is created with the same name ("twentytwentyfour") instead of taking on the name defined in the tool, and then the reference to the parent theme is "twenty-twenty-four" instead of "twentytwentyfour". 

Those two issues together mean that the resulting child theme is recognised as Twenty Twenty Four itself, instead of its child, and therefore tries to replace TT4 instead of simply being installed as its child. Then once I change the theme name of the child to something else and re-install, the theme is recognised as broken because it's a child theme without a valid parent (because it's looking for a theme called "twenty-twenty-four" rather than "twentytwentyfour".

**Comment by pbking** [comment]
Hrm... I wasn't able to reproduce this.

Is this using the wp-admin interface (depreciated?) or the tools in the editor?  If using the wp-admin interface can you try with the editor tools?

**Comment by bluebee-team** [comment]
Oh! Well that's embarrassing. I wasn't aware the wp-admin interface for this function had been depreciated. Editor tools work perfectly. My bad! Closing :)
