### ISSUE TITLE
clone of blockbase theme doesn't render patterns

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/create-block-theme#65]
Plugin creates clone of the theme successfully. 
But it creates with new directory structure for parts and templates but not for patterns.

`block-template-parts` => `parts`
`block-templates` => `templates`
`inc/patterns` => `inc/patterns`

UI doesn't render the patterns in the newly created theme.

**Comment by pbking** [comment]
Exporting Blockbase seems to work as expected (both as a clone and with child themes).  Including changing templates and patterns.  This appears to have been fixed at some point.  Closing as complete.  Please reopen if it continues to be a problem.
