### ISSUE TITLE
The Theme Check plugin sometimes returns "Both DOS and UNIX style line endings" error

### ISSUE THREAD

**Issue by mikachan** [WordPress/create-block-theme#680]
In version 2.3.0, sometimes the Theme Check plugin returns the following error:

> REQUIRED: Both DOS and UNIX style line endings were found in the file readme.txt. This causes a problem with SVN repositories and must be corrected before the theme can be accepted. Please change the file to use only one style of line endings.

This might be related to https://github.com/WordPress/create-block-theme/pull/662.

We might be able to fix this by using regex to normalise all new lines in the open text fields for the theme meta data.

To reproduce:

- Update the font credits and manually add image credits using the CBT UI
- Export the theme zip, install it on a local site, and run the Theme Check plugin

**Comment by matiasbenedetto** [comment]
I don't this issue is directly related to https://github.com/WordPress/create-block-theme/pull/662
I think this problem could arise from any user input added to the readme.txt settings containing DOS style new line characters.

**Comment by matiasbenedetto** [comment]
A potential fix for this issue: https://github.com/WordPress/create-block-theme/pull/681
