### ISSUE TITLE
Ability to reset all settings in one click

### ISSUE THREAD

**Issue by mikachan** [WordPress/create-block-theme#686]
This idea is from @carolinan from this GB issue: https://github.com/WordPress/gutenberg/issues/54958.

> I often find that I need to go to three places to reset changes:
>
> 1. The template management screen
> 2. The template part management screen
> 3. The styles sidebar
> 
> On the template and part management screens, I miss an option to reset all my items with one click.
> 
> In general I miss an option to reset all my user made changes, so both custom CSS, block style changes, template part markup changes, and template markup changes.
> 
> The option for me is to install and use a third party reset plugin, but those delete all my content and deactivate my current theme and plugins.

Related to https://github.com/WordPress/create-block-theme/issues/494.

**Comment by matiasbenedetto** [comment]
A potential implementation for this: https://github.com/WordPress/create-block-theme/pull/687
Feedback welcome!
