### ISSUE TITLE
Downloaded \zip is missing style.css

### ISSUE THREAD

**Issue by bph** [WordPress/create-block-theme#689]
I created a new theme with the plugin, added two templates, saved everything and then exported the zip file. On upload to a different site I got the error message "The package could not be installed. The theme is missing the style.css stylesheet."

This is the screenshot of the folder structure of the ~exported zip file~ wp-content/basic-templates folder on site. 
![Screenshot 2024-07-15 at 15 57 21](https://github.com/user-attachments/assets/468d36b9-2cd3-4b46-90f4-b9cbe831f6e4)

The zip file for testing, too. 
[basic-templates.zip](https://github.com/user-attachments/files/16235620/basic-templates.zip)

**Comment by matiasbenedetto** [comment]
Hi @bph :wave:  I'm getting these files by inspecting the [.zip file you attached ](https://github.com/user-attachments/files/16235620/basic-templates.zip). So the error message seems to be right, the `style.css` is missing. I don't know why you are seeing it in the [screenshot.](https://private-user-images.githubusercontent.com/39980/348732305-468d36b9-2cd3-4b46-90f4-b9cbe831f6e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTI1NjIsIm5iZiI6MTcyMTA1MjI2MiwicGF0aCI6Ii8zOTk4MC8zNDg3MzIzMDUtNDY4ZDM2YjktMmNkMy00YjQ2LTkwZjQtYjljYmU4MzFmNmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE0MDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlN2JiZTk4YmU3ZDU2YTlkM2MzZjc3NmYyNjQ3NDkwMjExYzdhZTM5Mjc4NjdkZDMwNjQxNjQ5MjY4ODhhMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qy0EbaGMFUunyrOenSgasTmZaZukFLsInbE4an5s3YA)

```
unzip -l basic-templates.zip 
Archive:  basic-templates.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2024-07-15 15:48   basic-templates/templates/
        0  2024-07-15 15:48   basic-templates/parts/
       54  2024-07-15 15:48   basic-templates/templates/templates/single.html
       52  2024-07-15 15:48   basic-templates/templates/templates/page.html
     1307  2024-07-15 15:48   basic-templates/templates/templates/index.html
     3717  2024-07-15 15:48   basic-templates/templates/templates/front-page.html
      475  2024-07-15 15:48   basic-templates/parts/footer.html
      980  2024-07-15 15:48   basic-templates/parts/header.html
      704  2024-07-15 15:48   basic-templates/theme.json
---------                     -------
     7289                     9 files
```

Could you add an screencast of the process to help to reproduce this?

**Comment by bph** [comment]
Oops, I made a typo and fixed in the description. The screenshot is from the theme folder of site where I created and edited the theme, and from which I clicked on export to zip.

**Comment by bph** [comment]
The steps to recreate:

- Appearance > Create Block theme 
- Click on **Create a new blank theme**
- Added a single post template
- Added a page template
- Added a front page template. 
- Clicked on Save Changes to the Theme 
- Made sure all checkboxes are checked 
- Click on Save changes
- Got a black screen
- Went to templates 
- Click on the Tools icon
- Clicked on Export to Zip 

Versions:  
- WordPress 6.6-RC3
- Create Block theme

**Comment by bph** [comment]
To be clear, the bug is **that the zip export didn't grab the style.css from the directory.**

**Comment by bph** [comment]
Also missing from the export: 

- screenshot.png
- readme.txt

**Comment by bph** [comment]
Oh, I didn't even notice before, the /templates folder also has an additional /templates folder child, with the list of templates. It explains, why I can't upload the theme even after I added the style.css  zip folder. 

I received the error message: 
"The package could not be installed. Template is missing. Standalone themes need to have a templates/index.html or index.php template file. Child themes need to have a Template header in the style.css stylesheet."

**Comment by bph** [comment]
Somehow this seems entirely borked... I try again with a clean installation.

**Comment by bph** [comment]
So I did it again, with very deliberate movements on a clean install, and it worked as it supposed to do. 
[basic-pauli.zip](https://github.com/user-attachments/files/16236321/basic-pauli.zip)

I close this issue for now, and will reopen when I get in trouble again... 

It was disconcerting that the first download was borked, but I can't reproduce it for now.
