### ISSUE TITLE
Typo: "them" should be "theme"

### ISSUE THREAD

**Issue by justintadlock** [WordPress/create-block-theme#69]
Typo on this line: https://github.com/WordPress/create-block-theme/blob/trunk/admin/class-create-block-theme-admin.php#L614

```php
<p><?php _e('Export your current block them with changes you made to Templates, Template Parts and Global Styles.', 'create-block-theme'); ?></p>
```

Reported by @bgardner via Twitter DM.

**Comment by MaggieCabrera** [comment]
Closed via #72
