### ISSUE TITLE
Bug: Something isn't right when selecting all options in Save Changes to Theme

### ISSUE THREAD

**Issue by beafialho** [WordPress/create-block-theme#691]
When I select all the options in Save Changes to theme, this is happening:

![Captura de ecrã 2024-07-19, às 10 29 21](https://github.com/user-attachments/assets/e6ec72fb-d3c1-4d61-aecf-f7dd0bbd8f8f)

The links that have a `#` are also having an issue with weird text showing up on the front end.

There's also this warning from Theme Check plugin:

```
WARNING: Found ="<?php esc_html_e in patterns/front-page.php. Use esc_attr_e() inside HTML attributes, and esc_url() for link attributes. A manual review is needed.

Line 36: <figure class='wp-block-image size-full'><img src='<?php echo esc_url( get_stylesheet_directory_uri() ); ?>/assets/images/mood_1-min.jpg' alt='<?php esc_html_e('', 'cottage');?>'/></figure>
```

**Comment by creativecoder** [comment]
I think the warning is coming from this: `alt='<?php esc_html_e('', 'cottage');?>'`.

We need to update the escaping functionality to correctly use `esc_attr_e` inside html attributes.

This change is part of https://github.com/WordPress/create-block-theme/pull/683. I think we should extract that part and land it separately.

**Comment by mikachan** [comment]
> I think we should extract that part and land it separately.

I agree, that way we can hopefully fix the bug in this issue separately.

**Comment by matiasbenedetto** [comment]
I'll split the attr part of https://github.com/WordPress/create-block-theme/pull/683 to fix this
