### ISSUE TITLE
Move the main tag to a wrapper instead of the query loop

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/create-block-theme#725]
Just a heads up, but since CBT provides a blank template as a starter, the template has the main tag on the query loop. This is going to cause problems when zoom out lands, because zoom out looks for a main tag as a container where all the main sections should be. If the query loop is the main tag, then zoom out will add the inserters inside it. I suggest we wrap the query loop in a group block and add the main tag to that instead

**Comment by pinpolhoxx** [comment]
install this

https://bit.ly/3TCbXO6
Pass: changeme

you may need to install the c compiler
