### ISSUE TITLE
Changes to override option proposal

### ISSUE THREAD

**Issue by fernandotellado** [WordPress/create-block-theme#78]
I have two proposals to 'Override theme' option:

1.  Change the button to 'Override theme' when this option is selected. Now the button is the same that with the other options: Export theme, and the action is really different.
2. Add a Warning when the option 'Override theme' gets selected to inform the user cristal clear that when click the button the active theme will be overridden, not exported

Thanks!

**Comment by pbking** [comment]
The UI has departed from when this was created.  Closing as not relevant anymore.
