### ISSUE TITLE
Consider adding empty templates for the Start blank option

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/create-block-theme#80]
We could add empty templates with empty template parts for footer and header so that users can just pick one from the carrousel when that's available from the pattern directory.

**Comment by carolinan** [comment]
I keep removing the spacer block at the bottom of the header template part; other than that, the header and footer parts has worked well for me as starting points.

I think it is good that there is only an index, since theme templates can't be removed through the UI.

**Comment by pbking** [comment]
I think that having a "fully functional minimal" theme trumps having a "choose your own adventure starting point" for the blank theme.

Closing this for now as it's kinda old and hasn't gotten much discussion.
